### ISSUE TITLE
支持继续更新，别搞静态方法了，ioc注入吧

### ISSUE THREAD

**Issue by xxf2103625** [2881099/csredis#11]
core中使用一段时间不管web，再操作时总会报redis连接异常，不知道什么原因
linux下没发现这问题，iis里的很多这种错误

`Unable to write data to the transport connection: 你的主机中的软件中止了一个已建立的连接。. System.IO.IOException: Unable to write data to the transport connection: 你的主机中的软件中止了一个已建立的连接。. ---> System.Net.Sockets.SocketException: 你的主机中的软件中止了一个已建立的连接。
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BufferedStream.ReadByteSlow()
   at System.IO.BufferedStream.ReadByte()
   at CSRedis.Internal.IO.RedisReader.ReadType()
   at CSRedis.Internal.IO.RedisReader.ExpectType(RedisMessage expectedType)
   at CSRedis.Internal.IO.RedisReader.ReadStatus(Boolean checkType)
   at CSRedis.Internal.Commands.RedisStatus.Parse(RedisReader reader)
   at CSRedis.Internal.RedisConnector.Call[T](RedisCommand`1 command)
   at CSRedis.RedisClient.Write[T](RedisCommand`1 command)`

**Comment by 2881099** [comment]
iis默认有回收机制，.net已经自带回收机制，考虑可以关闭iis自动回收功能，或者独立开端口运行，或者移步到linux平台部署。

如果喜欢ioc方式，可以自行注入(单例, 单例, 单例) CSRedisClient 对象，而不使用 RedisHelper 类。
本项目是绿色纯净的，ioc注入需要依赖其他模块，不考虑增加。

感谢反馈
