### ISSUE TITLE
stream的XAdd方法报错

### ISSUE THREAD

**Issue by markquxiao** [2881099/csredis#153]
你好，我在使用XAdd方法时，总是报CSRedis.RedisException: 'ERR Invalid stream ID specified as stream command argument'这个错误，代码如下，test程序还没看到例子，帮忙解决一下，谢谢
string strKey = "stream_test";
                string id = "*";
 ValueTuple<string, string>[] tup = new ValueTuple<string, string>[5];// ("22222", "33333");
                tup[0] = ("1111", "22222");

                aa.XAdd(strKey, 100, id, tup);

**Comment by 2881099** [comment]
stream类型的方法，还没测试呢

**Comment by markquxiao** [comment]
omg！！！有agenda吗

**Comment by 2881099** [comment]
只粗略做了测试，这个命令在控制台能执行吗。

最近半年主要在搞FreeSql，近期找时间完善下测试，如有兴趣欢迎pr

**Comment by markquxiao** [comment]
可以执行的，ok

**Comment by ErikXu** [comment]
@2881099 
组包(bytes)好像有点问题，好像MAXLEN参数不能带双引号，有办法去掉吗？

127.0.0.1:6379> "XADD" "mystream" "MAXLEN 128" 42-0 "field1" "value1"
(error) ERR Invalid stream ID specified as stream command argument

127.0.0.1:6379>  "XADD" "mystream" MAXLEN 128 "42-0" "field1" "value1"
"42-0"

127.0.0.1:6379> "XADD" "mystream" "" "42-0" "field1" "value1"
(error) ERR Invalid stream ID specified as stream command argument

127.0.0.1:6379> "XADD" "mystream" "42-0" "field1" "value1"
"42-0"

**Comment by 2881099** [comment]
@ErikXu @markquxiao 
难为兄弟们了，上午我把这些方法的语法都通过了测试

![image](https://user-images.githubusercontent.com/16286519/68556077-bb621300-046b-11ea-9ea7-38ff0c6d5704.png)

**Comment by 2881099** [comment]
单元测试：https://github.com/2881099/csredis/blob/master/test/CSRedisCore.Tests/CSRedisClientStreamTests.cs

**Comment by 2881099** [comment]
剩下的问题：
数据读取可能有问题（可能），因为现在测试没有实际测试数据，可以的话希望能一起加入测试。

**Comment by 2881099** [comment]
目前只在 CSRedisClient 的同步方法使用 stream 系列方法命令。
完善之后再加入到 异步方法，RedisHelper 。

**Comment by 2881099** [comment]
> @2881099
> 组包(bytes)好像有点问题，好像MAXLEN参数不能带双引号，有办法去掉吗？或者其它思路？
> 
> 127.0.0.1:6379> "XADD" "mystream" "MAXLEN 128" 42-0 "field1" "value1"
> (error) ERR Invalid stream ID specified as stream command argument
> 
> 127.0.0.1:6379> "XADD" "mystream" MAXLEN 128 "42-0" "field1" "value1"
> "42-0"
> 
> 127.0.0.1:6379> "XADD" "mystream" "" "42-0" "field1" "value1"
> (error) ERR Invalid stream ID specified as stream command argument
> 
> 127.0.0.1:6379> "XADD" "mystream" "42-0" "field1" "value1"
> "42-0"
> 
> 改了下组包逻辑，暂时是可以执行通过的，但可能会引入其它问题：
> [ErikXu@36b768a?diff=split](https://github.com/ErikXu/csredis/commit/36b768afa1ca2c085e6934bfc14a761519b2b936?diff=split)

命令组装之前可以处理，不用在 Prepare 上处理（以免出现其他未知的错误），我已经在 RedisCommand.cs 里处理了这些问题，语法问题已解决。

**Comment by ErikXu** [comment]
@2881099 你的处理方式会比较合理一点，写和删除组装的指令也比较合理
[172.17.0.1:46774] "XADD" "testXAdd01" "*" "f1" "v1" "f2" "v2"
[172.17.0.1:46774] "XADD" "testXAdd02" "*" "f1" "v1" "f2" "v2"
[172.17.0.1:46774] "XADD" "testXAdd03" "*" "MAXLEN" "128" "f1" "v1" "f2" "v2"
[172.17.0.1:46774] "XADD" "testXAdd04" "*" "MAXLEN" "~128" "f1" "v1" "f2" "v2"
[172.17.0.1:46774] "DEL" "testXAdd01" "testXAdd02" "testXAdd03" "testXAdd04"
[172.17.0.1:46774] "XADD" "testXAdd01" "42-0" "f1" "v1" "f2" "v2"
[172.17.0.1:46774] "XADD" "testXAdd02" "43-0" "MAXLEN" "128" "f1" "v1" "f2" "v2"
[172.17.0.1:46774] "XADD" "testXAdd03" "44-0" "MAXLEN" "~128" "f1" "v1" "f2" "v2"
[172.17.0.1:46774] "DEL" "testXAdd01" "testXAdd02" "testXAdd03" "testXAdd04"

读（可能）的问题我们也会继续跟踪下，感谢你的支持！

**Comment by ganqiyin** [comment]
**1-注释掉 TestBase 中的 清空指令**
`public TestBase() {
			//rds.NodesServerManager.FlushAll();
		}`
**2-循环添加**
`[Fact]
        public void XAdd()
        {
            for (var i = 0; i < 10; i++)
            {
                //if (i >= 5)
                //    Thread.Sleep(TimeSpan.FromSeconds(1));
                rds.XAdd("mystream", 5, "*", ($"k{i}", $"v{i}"));
            }
}`
**3-XRANGE 指令报错**
` [Fact]
        public void XRange()
        {
            rds.XRange("mystream", "-", "+", 1);
        }`

CSRedis.RedisProtocolException
  HResult=0x80131500
  Message=Unexpected response type: MultiBulk (expecting Bulk)
  Source=CSRedisCore
  StackTrace:
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes) in E:\GithubRepository\csredis\src\CSRedisClient.cs:line 511
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander) in E:\GithubRepository\csredis\src\CSRedisClient.cs:line 745
   at CSRedis.CSRedisClient.XRange(String key, String start, String end, Int64 count) in E:\GithubRepository\csredis\src\CSRedisClient.cs:line 4128
   at CSRedisCore.Tests.CSRedisClientStreamTests.XRange() in E:\GithubRepository\csredis\test\CSRedisCore.Tests\CSRedisClientStreamTests.cs:line 113

**但是根据 monitor 监控里面 输出的指令
在控制台输入执行，是没有问题的**
1573537345.944212 [0 192.168.188.1:2676] "PING"
^[[21~1573537350.825408 [0 192.168.188.1:2675] "XRANGE" "mystream" "-" "+" "COUNT" "100"
1573537388.634865 [0 127.0.0.1:38898] "XRANGE" "mystream" "-" "+" "COUNT" "100"
1573537506.116270 [0 127.0.0.1:38898] "XRANGE" "mystream" "-" "+" "COUNT" "100"
1573537509.111554 [0 127.0.0.1:38898] "XRANGE" "mystream" "-" "+" "COUNT" "100"
1573537661.430955 [0 192.168.188.1:2801] "PING"
1573537676.750741 [0 192.168.188.1:2807] "PING"
1573537676.753931 [0 192.168.188.1:2808] "PING"
1573537676.772152 [0 192.168.188.1:2809] "PING"
1573537676.779207 [0 192.168.188.1:2810] "PING"
1573537676.780387 [0 192.168.188.1:2811] "PING"
1573537676.780393 [0 192.168.188.1:2812] "PING"
1573537680.437176 [0 192.168.188.1:2811] "XRANGE" "mystream" "-" "+" "COUNT" "100"
1573537753.531040 [0 192.168.188.1:2835] "PING"
1573537753.535964 [0 192.168.188.1:2836] "PING"
1573537753.565291 [0 192.168.188.1:2837] "PING"
1573537753.565310 [0 192.168.188.1:2838] "PING"
1573537753.567683 [0 192.168.188.1:2840] "PING"
1573537753.567691 [0 192.168.188.1:2841] "PING"
1573537754.812138 [0 192.168.188.1:2841] "XRANGE" "mystream" "-" "+" "COUNT" "1"


127.0.0.1:6379> "XRANGE" "mystream" "-" "+" "COUNT" "100"
 1) 1) "1573524686958-0"
    2) 1) "k0"
       2) "v0"
 2) 1) "1573524686959-0"
    2) 1) "k1"
       2) "v1"
 3) 1) "1573524686959-1"
    2) 1) "k2"
       2) "v2"
 4) 1) "1573524686959-2"
    2) 1) "k3"
       2) "v3"
 5) 1) "1573524686960-0"
    2) 1) "k4"
       2) "v4"
 6) 1) "1573524686960-1"
    2) 1) "k5"
       2) "v5"
 7) 1) "1573524686961-0"
    2) 1) "k6"
       2) "v6"
 8) 1) "1573524686961-1"
    2) 1) "k7"
       2) "v7"
 9) 1) "1573524686961-2"
    2) 1) "k8"
       2) "v8"
10) 1) "1573524686962-0"
    2) 1) "k9"

**Comment by 2881099** [comment]
收到

**Comment by 2881099** [comment]
XRange XRevRage 两个读取数据已修正

**Comment by 2881099** [comment]
@ganqiyin XRange XRevRage 两个读取数据已修正

**Comment by 2881099** [comment]
XInfo XPending XClaim 读取数据我这边调好了，也测试了一下

**Comment by ganqiyin** [comment]
> XInfo XPending XClaim 读取数据我这边调好了，也测试了一下

感谢，我今天在测试一下，因为项目需要，所以得测好才行

**Comment by 2881099** [comment]
> > XInfo XPending XClaim 读取数据我这边调好了，也测试了一下
> 
> 感谢，我今天在测试一下，因为项目需要，所以得测好才行

好的，有问题及时反馈，我配合修复协议问题

**Comment by CaiRuSen** [comment]
> 目前只在 CSRedisClient 的同步方法使用 stream 系列方法命令。
> 完善之后再加入到 异步方法，RedisHelper 。

现在好像还没加入的样子哈哈

**Comment by 2881099** [comment]
@CaiRuSen 

https://github.com/2881099/FreeRedis
重新写的 redis 客户端组件
