### ISSUE TITLE
list大小超过163771461时，csredis出现崩溃

### ISSUE THREAD

**Issue by markquxiao** [2881099/csredis#154]
读取和写入都会出现崩溃，C#崩溃堆栈如下所示：

日志名称:          Application
来源:            .NET Runtime
日期:            2019/7/30 19:22:23
事件 ID:         1026
任务类别:          无
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           C_win7_01
描述:
Application: yihangRedisDataSync.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: CSRedis.RedisClientException
   at CSRedis.CSRedisClient.GetAndExecute[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](CSRedis.RedisClientPool, System.Func`2<SafeObjectPool.Object`1<CSRedis.RedisClient>,System.__Canon>, Int32, Int32)
   at CSRedis.CSRedisClient.ExecuteScalar[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, System.Func`3<SafeObjectPool.Object`1<CSRedis.RedisClient>,System.String,System.__Canon>)
   at CSRedis.CSRedisClient.RPop(System.String)
   at RedisHelper.RPop(System.String)
   at yihangRedisDataSync.Form1.ListPop()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-07-30T11:22:23.000000000Z" />
    <EventRecordID>723</EventRecordID>
    <Channel>Application</Channel>
    <Computer>C_win7_01</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: yihangRedisDataSync.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: CSRedis.RedisClientException
   at CSRedis.CSRedisClient.GetAndExecute[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](CSRedis.RedisClientPool, System.Func`2&lt;SafeObjectPool.Object`1&lt;CSRedis.RedisClient&gt;,System.__Canon&gt;, Int32, Int32)
   at CSRedis.CSRedisClient.ExecuteScalar[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, System.Func`3&lt;SafeObjectPool.Object`1&lt;CSRedis.RedisClient&gt;,System.String,System.__Canon&gt;)
   at CSRedis.CSRedisClient.RPop(System.String)
   at RedisHelper.RPop(System.String)
   at yihangRedisDataSync.Form1.ListPop()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

</Data>
  </EventData>
</Event>

**Comment by 2881099** [comment]
能看见错误信息不？

**Comment by markquxiao** [comment]
看不到错误信息了，我们后来增加了cpu核数，内存，后来再没出问题了，而且list存取速度也快了
