### ISSUE TITLE
endpipe报Queue empty

### ISSUE THREAD

**Issue by mushramb0** [2881099/csredis#160]
**我代码是这样写的**
RedisHelper
                    .StartPipe()
                    .ZAdd($"{input.appName}:version", (ts, input.version))
                    .ZAdd($"{key}:nick", (ts, input.nick))
                    .ZAdd($"{key}:ip", (ts, input.ip))
                    .ZAdd($"{key}:addr", (ts, input.addr))
                    .ZAdd($"{key}:mac", (ts, input.mac))
                    .EndPipe();
**但是会报异常**
System.InvalidOperationException: Queue empty.
   at System.Collections.Generic.Queue`1.ThrowForEmptyQueue()
   at System.Collections.Generic.Queue`1.Dequeue()
   at CSRedis.CSRedisClientPipe`1.EndPipe()
   at Czkj.FatChicken.Controllers.TaobaoTaskController.CalcOnlineByPipe(DownloadTaskInput input) in C:\Users\Administrator\source\repos\Czkj.NamoService\Services\Czkj.FatChicken\Controllers\TaobaoTaskController.cs:line 115
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Czkj.Common.Middlewares.ErrorLoggerMiddleware.Invoke(HttpContext context) in C:\Users\Administrator\source\repos\Czkj.NamoService\Czkj.Common\Middlewares\ErrorLoggerMiddleware.cs:line 72

**而且gc回收的时候还会报如下错误,导致应用池经常性重启**
Unhandled Exception: System.InvalidOperationException: Queue empty.
   at System.Collections.Generic.Queue`1.ThrowForEmptyQueue()
   at System.Collections.Generic.Queue`1.Dequeue()
   at CSRedis.CSRedisClientPipe`1.EndPipe()
   at CSRedis.CSRedisClientPipe`1.Dispose()
   at CSRedis.CSRedisClientPipe`1.Finalize()

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/62912678-c5686d00-bdbb-11e9-972b-13be2ce8550a.png)
尝试测试了一把

**Comment by mushramb0** [comment]
是的 他只是偶尔报 几分钟一次 这是我的日志
Application started. Press Ctrl+C to shut down.
[Error]-[2019-08-13 10:22:37.0101]-[Controllers.TaobaoTaskController]
Queue empty.
[Error]-[2019-08-13 10:24:35.9063]-[Controllers.TaobaoTaskController]
Queue empty.
[Error]-[2019-08-13 10:27:37.8370]-[Controllers.TaobaoTaskController]
Queue empty.
[Error]-[2019-08-13 10:36:36.0602]-[Controllers.TaobaoTaskController]
Queue empty.
[Error]-[2019-08-13 10:36:42.4291]-[Controllers.TaobaoTaskController]
Queue empty.
[Error]-[2019-08-13 10:39:42.8922]-[Controllers.TaobaoTaskController]
Queue empty.
[Error]-[2019-08-13 10:40:43.3985]-[Controllers.TaobaoTaskController]
Queue empty.
[Error]-[2019-08-13 10:41:38.4597]-[Controllers.TaobaoTaskController]
Queue empty.
[Error]-[2019-08-13 10:49:14.2580]-[Controllers.TaobaoTaskController]
Queue empty.
[Error]-[2019-08-13 10:52:08.8511]-[Controllers.TaobaoTaskController]
Queue empty.
[Error]-[2019-08-13 10:56:37.4186]-[Controllers.TaobaoTaskController]
Queue empty.
[Error]-[2019-08-13 10:57:52.8894]-[Controllers.TaobaoTaskController]
Queue empty.

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/62913198-c4d0d600-bdbd-11e9-9a0a-120d40e4450a.png)

错误报 Dequeue 时，Queue empty.

看源码里如果 Empty 的话执行不到现在的逻辑。大概知道什么原因了，可能是 gc 线程冲突的问题

试试加上 using()

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/62913384-68ba8180-bdbe-11e9-90cd-cdab5ece4bd0.png)

我写了个线程里死循环，没有出现错误。你现在用的哪个版本

**Comment by mushramb0** [comment]
是啊 我用的是3.1.2 我也看了源码 百思不得其解 好郁闷

**Comment by mushramb0** [comment]
我整个代码是这样写的

`[HttpPost]
        public ActionResult CalcOnlineByPipe(DownloadTaskInput input)
        {
            try
            {
                if (string.IsNullOrEmpty(input.appName)) input.appName = "_";
                if (string.IsNullOrEmpty(input.version)) input.version = "_";
                var ts = DateTime.Now.GetUtcSeconds();
                var key = $"{input.appName}:{input.version}";
                var _ = RedisHelper
                    .StartPipe()
                    .ZAdd($"{input.appName}:version", (ts, input.version))
                    .ZAdd($"{key}:nick", (ts, input.nick))
                    .ZAdd($"{key}:ip", (ts, input.ip))
                    .ZAdd($"{key}:addr", (ts, input.addr))
                    .ZAdd($"{key}:mac", (ts, input.mac))
                    .EndPipe();
                key = $"{input.appName}";
                _ = RedisHelper
                    .StartPipe()
                    .ZAdd($"{key}:nick", (ts, input.nick))
                    .ZAdd($"{key}:ip", (ts, input.ip))
                    .ZAdd($"{key}:addr", (ts, input.addr))
                    .ZAdd($"{key}:mac", (ts, input.mac))
                    .HSet($"{input.appName}:ip_nick_hash", input.ip, input.nick)
                    .EndPipe();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }
            return Ok();
        }`

**Comment by 2881099** [comment]
```csharp
[HttpPost]
        public ActionResult CalcOnlineByPipe(DownloadTaskInput input)
        {
            try
            {
                if (string.IsNullOrEmpty(input.appName)) input.appName = "";
                if (string.IsNullOrEmpty(input.version)) input.version = "";
                var ts = DateTime.Now.GetUtcSeconds();
                var key = $"{input.appName}:{input.version}";
                using (var pipe = RedisHelper.StartPipe()) {
                    var _ = pipe
                        .ZAdd($"{input.appName}:version", (ts, input.version))
                        .ZAdd($"{key}:nick", (ts, input.nick))
                        .ZAdd($"{key}:ip", (ts, input.ip))
                        .ZAdd($"{key}:addr", (ts, input.addr))
                        .ZAdd($"{key}:mac", (ts, input.mac));
                }
                key = $"{input.appName}";
                using (var pipe = RedisHelper.StartPipe())
                {
                    var _ = pipe
                        .ZAdd($"{key}:nick", (ts, input.nick))
                        .ZAdd($"{key}:ip", (ts, input.ip))
                        .ZAdd($"{key}:addr", (ts, input.addr))
                        .ZAdd($"{key}:mac", (ts, input.mac))
                        .HSet($"{input.appName}:ip_nick_hash", input.ip, input.nick);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }
            return Ok();
        }
```

这样试试

**Comment by 2881099** [comment]
3.1.2 改出逻辑 bug 了，先退回 3.0.66 吧，或者稍后下载 3.1.4

**Comment by mushramb0** [comment]
ok 我刚刚更新了3.1.4还是有那个问题 另外加using只能防止应用池重启了

**Comment by 2881099** [comment]
之前有使用过这个方法吗

**Comment by mushramb0** [comment]
之前没有用过

**Comment by 2881099** [comment]
运行环境描述下

**Comment by mushramb0** [comment]
iis10 inprocess模式+netcore2.2 我刚修改了源码调试了一下 发现不知道为啥endpipe还没有执行完毕 析构函数就被调用了 导致endpipe函数又被调用了一次

**Comment by 2881099** [comment]
所以我把这块代码改回去了，去掉了析构函数

**Comment by 2881099** [comment]
v3.1.4，或者看最新的源码

**Comment by mushramb0** [comment]
为什么析构函数会提早被调用了 好奇怪

**Comment by 2881099** [comment]
不好意思，代码没生效。。。3.1.4 还是旧的

**Comment by 2881099** [comment]
> 为什么析构函数会提早被调用了 好奇怪

这是 bug，最近3.1.x版本改出来的bug，我去掉析构函数了

**Comment by mushramb0** [comment]
好的 是某段代码手动调用了吗 不是gc自动回收造成的吧

**Comment by 2881099** [comment]
是 gc，gc 太厉害了

**Comment by mushramb0** [comment]
这个是为什么 能讲讲吗

**Comment by 2881099** [comment]
看下 PipeCommand 方法就知道了

**Comment by 2881099** [comment]
是 bug，最近几天改出来的

**Comment by mushramb0** [comment]
是每次流式调用时都new一个CSRedisClientPipe吗

**Comment by 2881099** [comment]
当前这次，与上一次类型不同时，会 new 一个新的。
