### ISSUE TITLE
can't figure out why this happend

### ISSUE THREAD

**Issue by vincentelite** [2881099/csredis#178]
|ERROR|Microsoft.AspNetCore.Session.SessionMiddleware|Error closing the session. System.IO.EndOfStreamException: Unexpected end of stream; expected type 'MultiBulk'; data = 
   at CSRedis.CSRedisClient.GetAndExecuteAsync[T](RedisClientPool pool, Func`2 handerAsync, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalarAsync[T](String key, Func`3 handerAsync)
   at CSRedis.CSRedisClient.HMGetAsync(String key, String[] fields)
   at Microsoft.Extensions.Caching.Redis.CSRedisCache.GetAndRefreshAsync(String key, Boolean getData, CancellationToken token)
   at Microsoft.Extensions.Caching.Redis.CSRedisCache.RefreshAsync(String key, CancellationToken token)
   at Microsoft.AspNetCore.Session.DistributedSession.CommitAsync(CancellationToken cancellationToken)

**Comment by vincentelite** [comment]
we follow the doc exactly and still got no clue about why EndOfStreamException, (plus:we host the core app in linux )

**Comment by 2881099** [comment]
Which version are you using?

**Comment by vincentelite** [comment]
core 2.2

**Comment by 2881099** [comment]
Did redis-server turn SSL on?

**Comment by vincentelite** [comment]
nope

**Comment by 2881099** [comment]
https://github.com/2881099/Microsoft.Extensions.Caching.CSRedis/blob/master/CSRedisCache.cs

You can try that.

Change the asynchronous method in the link to synchronization. Put it into project operation.

Reason: Synchronization and asynchronization are implemented differently, using SocketEventArgs asynchronously.

**Comment by 2881099** [comment]
If we confirm that the asynchronous method fails, we will improve it

SocketEventArgs may be abandoned by the Microsoft. net team.

Strangely enough, we haven't encountered this mistake yet.

**Comment by vincentelite** [comment]
we'll try it tomorrow due to the other issue,we'll keep you updated. Thank you all the same

**Comment by 2881099** [comment]
从这些线索分析。

使用异步方法的时候，有可能SocketEventArgs事件有误，触发完成的事件，但是数据并没有到达，导致读取失败的错误。

------------

From these clues analysis.

When using the asynchronous method, it is possible that the SocketEventArgs event is wrong and triggers the completed event, but the data has not arrived, resulting in the error of reading failure.

![image](https://user-images.githubusercontent.com/16286519/65145983-6a2a3a00-da4d-11e9-9fc0-cc072261fb32.png)

Return value - 1 when data cannot be read.

**Comment by 2881099** [comment]
1. If redis-server is blocked, the data may not be read. This is also a factor in judgment.
2. Are you using redis-server for remote access? Long-distance network access may also be blocked, although this probability is small.

The default reading time-out is 10 seconds. The parameter "syncTimeout" can be changed.
Redis is a single thread model. Minimize blocking command operations.

**Comment by 2881099** [comment]
Because I can't make this mistake here.
Would you please download the source code and introduce project observation?
