### ISSUE TITLE
请问ICacheService正确使用方式

### ISSUE THREAD

**Issue by Holo-k** [2881099/csredis#179]
![Annotation 2019-09-19 094624](https://user-images.githubusercontent.com/24891711/65205441-1b69b800-dac0-11e9-84e8-04a6f0aec14d.jpg)
![Annotation 2019-09-19 094702](https://user-images.githubusercontent.com/24891711/65205451-1d337b80-dac0-11e9-8935-50b802be460b.jpg)
使用单例下创建CSRedisClient在访问Cache时出现了数据库Disposed问题，然后我更改成在每一个ICacheService实现方法里用using new CSRedisClient这个方法可以撑住一会，并发一上来也出现数据库Disposed问题，求正确的操作方式

**Comment by 2881099** [comment]
这样是对的

**Comment by 2881099** [comment]
```csharp
var running = true;
            AppDomain.CurrentDomain.ProcessExit += (s1, e1) =>
            {
                running = false;
            };
            Console.CancelKeyPress += (s1, e1) =>
            {
                running = false;
            };
```

方便测试下这两事件吗，写个日志。

目前只有这两事件，和 csredis.Dispose() 方法会导致这个错误发生。

**Comment by Holo-k** [comment]
报错并没有触发这2个事件。
日志记录如下：
fail: Surging.Core.CPlatform.Runtime.Server.Implementation.DefaultServiceExecutor[0]
      执行本地逻辑时候发生了错误。
System.ObjectDisposedException: Cannot access a disposed object.
Object name: '【127.0.0.1:6379/13】对象池已释放，无法访问。'.
   at SafeObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
   at SafeObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Exists(String key)
   at RedisHelper`1.Exists(String key)
   at InternetCADSystem.ModuleServices.ServiceStackRedis.ContainsKey(String key) in E:\Ex\Work_Test\New folder\InternetCADSystem-develop\InternetCADSystem-develop\Src\InternetCADSystem.ModuleServices\RedisCache.cs:line 118
   at InternetCADSystem.ModuleServices.RedisCache.ContainsKey[TV](String key) in E:\Ex\Work_Test\New folder\InternetCADSystem-develop\InternetCADSystem-develop\Src\InternetCADSystem.ModuleServices\RedisCache.cs:line 32
   at InternetCADSystem.ModuleServices.RedisCache.GetOrCreate[TV](String cacheKey, Func`1 create, Int32 cacheDurationInSeconds) in E:\Ex\Work_Test\New folder\InternetCADSystem-develop\InternetCADSystem-develop\Src\InternetCADSystem.ModuleServices\RedisCache.cs:line 47
   at SqlSugar.CacheSchemeMain.GetOrCreate[T](ICacheService cacheService, QueryBuilder queryBuilder, Func`1 getData, Int32 cacheDurationInSeconds, SqlSugarClient context)
   at SqlSugar.QueryableProvider`1._ToList[TResult]()
   at SqlSugar.QueryableProvider`1.ToList()
   at SqlSugar.QueryableProvider`1.First()
   at SqlSugar.QueryableProvider`1.<FirstAsync>b__129_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at InternetCADSystem.ModuleServices.System.AppInfoService.GetAppPollTime() in E:\Ex\Work_Test\New folder\InternetCADSystem-develop\InternetCADSystem-develop\Src\InternetCADSystem.ModuleServices\System\AppInfoService.cs:line 74
   at Surging.Core.CPlatform.Runtime.Server.Implementation.DefaultServiceExecutor.LocalExecuteAsync(ServiceEntry entry, RemoteInvokeMessage remoteInvokeMessage, RemoteInvokeResultMessage resultMessage)
fail: Surging.Core.CPlatform.Runtime.Server.Implementation.DefaultServiceExecutor[0]
      执行本地逻辑时候发生了错误。
System.ObjectDisposedException: Cannot access a disposed object.
Object name: '【127.0.0.1:6379/13】对象池已释放，无法访问。'.
   at SafeObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
   at SafeObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Exists(String key)
   at RedisHelper`1.Exists(String key)
   at InternetCADSystem.ModuleServices.ServiceStackRedis.ContainsKey(String key) in E:\Ex\Work_Test\New folder\InternetCADSystem-develop\InternetCADSystem-develop\Src\InternetCADSystem.ModuleServices\RedisCache.cs:line 118
   at InternetCADSystem.ModuleServices.RedisCache.ContainsKey[TV](String key) in E:\Ex\Work_Test\New folder\InternetCADSystem-develop\InternetCADSystem-develop\Src\InternetCADSystem.ModuleServices\RedisCache.cs:line 32
   at InternetCADSystem.ModuleServices.RedisCache.GetOrCreate[TV](String cacheKey, Func`1 create, Int32 cacheDurationInSeconds) in E:\Ex\Work_Test\New folder\InternetCADSystem-develop\InternetCADSystem-develop\Src\InternetCADSystem.ModuleServices\RedisCache.cs:line 47
   at SqlSugar.CacheSchemeMain.GetOrCreate[T](ICacheService cacheService, QueryBuilder queryBuilder, Func`1 getData, Int32 cacheDurationInSeconds, SqlSugarClient context)
   at SqlSugar.QueryableProvider`1._ToList[TResult]()
   at SqlSugar.QueryableProvider`1.ToList()
   at SqlSugar.QueryableProvider`1.First()
   at InternetCADSystem.ModuleServices.System.BusinessLogService.GetUser(SqlSugarClient db, String userId) in E:\Ex\Work_Test\New folder\InternetCADSystem-develop\InternetCADSystem-develop\Src\InternetCADSystem.ModuleServices\System\BusinessLogService.cs:line 42
   at InternetCADSystem.ModuleServices.System.BusinessLogService.<>c__DisplayClass7_0.<TranslateLog>b__0(BusinessLog l) in E:\Ex\Work_Test\New folder\InternetCADSystem-develop\InternetCADSystem-develop\Src\InternetCADSystem.ModuleServices\System\BusinessLogService.cs:line 78
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at InternetCADSystem.ModuleServices.System.BusinessLogService.TranslateLog(SqlSugarClient db, List`1 package) in E:\Ex\Work_Test\New folder\InternetCADSystem-develop\InternetCADSystem-develop\Src\InternetCADSystem.ModuleServices\System\BusinessLogService.cs:line 70
   at InternetCADSystem.ModuleServices.System.BusinessLogService.Log(List`1 package) in E:\Ex\Work_Test\New folder\InternetCADSystem-develop\InternetCADSystem-develop\Src\InternetCADSystem.ModuleServices\System\BusinessLogService.cs:line 32
   at Surging.Core.CPlatform.Runtime.Server.Implementation.DefaultServiceExecutor.LocalExecuteAsync(ServiceEntry entry, RemoteInvokeMessage remoteInvokeMessage, RemoteInvokeResultMessage resultMessage)

**Comment by Holo-k** [comment]
还有另外一个日志：
fail: Surging.Core.DotNetty.DotNettyTransportClientFactory[0]
      消息发送失败。
Surging.Core.CPlatform.Exceptions.CPlatformCommunicationException: Cannot access a disposed object.
Object name: '【127.0.0.1:6379/13】对象池已释放，无法访问。'.
   at Surging.Core.CPlatform.Transport.Implementation.TransportClient.RegisterResultCallbackAsync(String id)
   at Surging.Core.CPlatform.Transport.Implementation.TransportClient.SendAsync(RemoteInvokeMessage message)
fail: Surging.Core.CPlatform.Runtime.Client.Implementation.RemoteInvokeService[0]
      发起请求中发生了错误，服务Id：InternetCADSystem.IModuleServices.System.IAppInfoService.GetAppPollTime。错误信息：Cannot access a disposed object.
      Object name: '【127.0.0.1:6379/13】对象池已释放，无法访问。'.
Surging.Core.CPlatform.Exceptions.CPlatformCommunicationException: Cannot access a disposed object.
Object name: '【127.0.0.1:6379/13】对象池已释放，无法访问。'.
   at Surging.Core.CPlatform.Transport.Implementation.TransportClient.RegisterResultCallbackAsync(String id)
   at Surging.Core.CPlatform.Transport.Implementation.TransportClient.SendAsync(RemoteInvokeMessage message)
   at Surging.Core.CPlatform.Utilities.CancellationTokenExtensions.WithCancellation[T](Task`1 task, Int32 requestTimeout)
   at Surging.Core.CPlatform.Runtime.Client.Implementation.RemoteInvokeService.InvokeAsync(RemoteInvokeContext context, Int32 requestTimeout)
dbug: InternetCADSystem.AppApi.Filers.LogFilter[0]
      Result:{"Value":{"Data":{"AccessToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiMzgwMDEiLCJleHAiOjE1NjkxMzE3MDcsImlzcyI6Ik5ndyIsImF1ZCI6IkNBRCJ9.EWt7WIuzZ4r4TQWWyEcBP-IsmloOqn3yiEsuzfaf1XE","ExpiresIn":259200,"TokenType":"Bearer","Role":2,"IsNegotiator":false,"PollTime":15},"Status":0},"Formatters":[],"ContentTypes":[],"DeclaredType":null,"StatusCode":200}
fail: Surging.Core.DotNetty.DotNettyTransportClientFactory[0]
      消息发送失败。
Surging.Core.CPlatform.Exceptions.CPlatformCommunicationException: Cannot access a disposed object.
Object name: '【127.0.0.1:6379/13】对象池已释放，无法访问。'.
   at Surging.Core.CPlatform.Transport.Implementation.TransportClient.RegisterResultCallbackAsync(String id)
   at Surging.Core.CPlatform.Transport.Implementation.TransportClient.SendAsync(RemoteInvokeMessage message)
fail: Surging.Core.CPlatform.Runtime.Client.Implementation.RemoteInvokeService[0]
      发起请求中发生了错误，服务Id：InternetCADSystem.IModuleServices.System.IBusinessLogService.Log_package。错误信息：Cannot access a disposed object.
      Object name: '【127.0.0.1:6379/13】对象池已释放，无法访问。'.
Surging.Core.CPlatform.Exceptions.CPlatformCommunicationException: Cannot access a disposed object.
Object name: '【127.0.0.1:6379/13】对象池已释放，无法访问。'.
   at Surging.Core.CPlatform.Transport.Implementation.TransportClient.RegisterResultCallbackAsync(String id)
   at Surging.Core.CPlatform.Transport.Implementation.TransportClient.SendAsync(RemoteInvokeMessage message)
   at Surging.Core.CPlatform.Utilities.CancellationTokenExtensions.WithCancellation[T](Task`1 task, Int32 requestTimeout)
   at Surging.Core.CPlatform.Runtime.Client.Implementation.RemoteInvokeService.InvokeAsync(RemoteInvokeContext context, Int32 requestTimeout)

**Comment by 2881099** [comment]
不好意思。今天适配 FreeSql odbc 访问库，忙到忘了回复。

你那边可以调试吗？如果能就最好，打断点看执行，如果不行就记录日志。
下载源码，CSRedisCore、SafeObjectPool，在项目内引用。

在 SafeObjectPool 项目记录日志或者调试，在 ObjectPool.cs 搜索 running，这个是上面错误的判断条件，目前只有在 262 行，或者 SafeObjectPool 实例.Dispose 方法会将其改为 false。

https://github.com/2881099/SafeObjectPool 源码在这里。

**Comment by Holo-k** [comment]
抱歉，回复晚了。我自己新建一个简单的API项目测试几次都没有发现问题。估计是我的项目使用surging操作不当的问题才会造成这个，但是目前没有办法解决这个问题，为了要项目先跑起来，就把sqlsugar里面使用缓存的功能暂时取消先。你的库应该是没有问题的，我有空就测试一下。

**Comment by 2881099** [comment]
了解了
