### ISSUE TITLE
关于发布订阅

### ISSUE THREAD

**Issue by wanghaoxing** [2881099/csredis#184]
直接使用list的lpush跟lpop做消息的的发布订阅刚觉更简单啊，跟暴漏出来的publish有什么区别

**Comment by 2881099** [comment]
publish 是 redis 长连接订阅功能，程序重启的时候应该接收到的消息会丢失。

list lpush lpop 效率低一点，消息保障性好一点，程序重启没影响。

**Comment by wanghaoxing** [comment]
我使用csredis会报这个错csreids 错误
```
【172.16.0.146:6379/0】：Unable to read data from the transport connection: Connection timed out. at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
at CSRedis.CSRedisClient.LPop(String key)
at RedisHelper`1.LPop(String key)
```

**Comment by 2881099** [comment]
idleTimeout 调一下，大于5秒，小于服务器设置断开的时间
