### ISSUE TITLE
SafeObjectPool.Get 获取超时（10秒），设置 Policy.IsThrowGetTimeoutException 可以避免该异常。

### ISSUE THREAD

**Issue by catwarrior** [2881099/csredis#196]
asp.net core 2.1
使用用csredis
最近比较频繁的报如下错误信息：

Message: SafeObjectPool.Get 获取超时（10秒），设置 Policy.IsThrowGetTimeoutException 可以避免该异常。
Exception: System.TimeoutException: SafeObjectPool.Get 获取超时（10秒），设置 Policy.IsThrowGetTimeoutException 可以避免该异常。
   at SafeObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Eval(String script, String key, Object[] args)
   at Microsoft.Extensions.Caching.Redis.CSRedisCache.Set(String key, Byte[] value, DistributedCacheEntryOptions options)
   at Microsoft.Extensions.Caching.Distributed.IDistributedCacheExtensions.SetObject(IDistributedCache cache, String key, Object value, DistributedCacheEntryOptions options)

使用方式（IDistributedCache）
CSRedis.CSRedisClient csredis = new CSRedis.CSRedisClient(configurationRoot["CacheOption:Connection"]);
            RedisHelper.Initialization(csredis);
            services.AddSingleton<IDistributedCache>(new Microsoft.Extensions.Caching.Redis.CSRedisCache(RedisHelper.Instance));

**Comment by 2881099** [comment]
poolsize 设置多大？
类似管道的操作，是否都正常关闭了？
有没有使用订阅操作，订阅了多少个？
监视RedisHelper.Nodes.First().Value. Statistics统计属性，他的格式是 可用数/总数量

**Comment by catwarrior** [comment]
@2881099 
配置：
defaultDatabase=13,poolsize=20,preheat=true,ssl=false,writeBuffer=1024
没有使用管道操作。
调用使用的是 SetObject方法。
因为用的是IDistributedCache接口，注册的时候是单例，没有地方显示的关闭。

好的我加下statistics， 顺便问下，因为我的应用是一个集群，Statistics是统计客户端信息的统计吗？

**Comment by 2881099** [comment]
可以，如果是集群，RedisHelper.Instance.Nodes 会有多个，一起打印出来

**Comment by catwarrior** [comment]
@2881099
poolsize的设置有什么建议
设置多大合适？ 设置大了有什么负面的影响？

感谢!

**Comment by 2881099** [comment]
设大点没事，1000，预热preheat设小的

**Comment by catwarrior** [comment]
preheat这个值也可以设置成xx? 

preheat设置成true预热多少个连接?

**Comment by 2881099** [comment]
preheat=true 预热 poolsize 个连接（启动的时候会很慢），也可以设置为数字。

如果服务器自动断开不活跃的连接，请求量不大，预热太大没有用，因为过一会连接不用就会服务器断开，白预热。

如果并发过大，在程序启动前预热好连接有用。
