### ISSUE TITLE
并发连接大的时候出现大量“对象池已释放，无法访问。”错误信息

### ISSUE THREAD

**Issue by rteam** [2881099/csredis#198]
最近把redis缓存驱动从StackExchange.Redis换成csredis，以前的超时错误没有了，但有一个新的问题，就是并发连接大的时候会出现大量“对象池已释放，无法访问。”错误信息
应用是通过k8s部署到linux上，出现错误信息的服务部署了20个实例，每个实例1u1g
做压力测试的时候并发一上2000则会出现大量一下错误

`System.ObjectDisposedException: Cannot access a disposed object.
Object name: '【192.168.41.121:6379/0】对象池已释放，无法访问。'.
at SafeObjectPool.ObjectPool`1.getFree(System.Boolean checkAvailable) at offset 46
at SafeObjectPool.ObjectPool`1.Get(System.Nullable`1 timeout) at offset 1
at CSRedis.CSRedisClient.GetAndExecute[T](CSRedis.RedisClientPool pool, System.Func`2 handler, System.Int32 jump, System.Int32 errtimes) at offset 27
at CSRedis.CSRedisClient.ExecuteScalar[T](System.String key, System.Func`3 hander) at offset 188
at CSRedis.CSRedisClient.Get[T](System.String key) at offset 28
at RedisHelper`1.Get[T](System.String key) at offset 5
at Ouchn.Core.Cache.SimpleRedisCacheManager`1.TryGetOrAdd(System.String Key, System.Func`2 valueFactory, Ouchn.Core.Cache.TCacheValue& value) at offset 33
at Ouchn.LearningPortfolio.DomainService.GradeDomainService.FindCourseGradesBySchoolRoll(System.String SchoolRollId) at offset 80 in /var/lib/jenkins/workspace/Ouchn.LearningPortfolio/Ouchn.LearningPortfolio.DomainService/GradeDomainService.cs:line 133:col 13
at lambda_method(System.Runtime.CompilerServices.Closure, System.Object, System.Object[])
at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(System.Object target, System.Object[] parameters)
at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(Microsoft.AspNetCore.Mvc.Infrastructure.IActionResultTypeMapper mapper, Microsoft.Extensions.Internal.ObjectMethodExecutor executor, System.Object controller, System.Object[] arguments)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext() at offset 198
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at offset 12
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) at offset 46
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext() at offset 165
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at offset 12
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context) at offset 32
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(Microsoft.AspNetCore.Mvc.Internal.State& next, Microsoft.AspNetCore.Mvc.Internal.Scope& scope, System.Object& state, System.Boolean& isCompleted) at offset 905
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__13.MoveNext() at offset 47
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at offset 12
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) at offset 46
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext() at offset 166
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at offset 12
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(Microsoft.AspNetCore.Mvc.Filters.ResourceExecutedContext context) at offset 32
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(Microsoft.AspNetCore.Mvc.Internal.State& next, Microsoft.AspNetCore.Mvc.Internal.Scope& scope, System.Object& state, System.Boolean& isCompleted) at offset 2123
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext() at offset 47
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at offset 12
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) at offset 46
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext() at offset 302
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at offset 12
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) at offset 46
at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext() at offset 459
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at offset 12
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) at offset 46
at Exceptionless.AspNetCore.ExceptionlessMiddleware.<Invoke>d__3.MoveNext() at offset 115`

请问这是什么原因？连接参数都是默认值，没有变，是否需要调整设置？连接redis是内网主机，该redis实例最大并发连接30000
谢谢。

**Comment by 2881099** [comment]
CSRedisClient 定义了多少次，RedisHelpr.Init 运行了多少次。这个错误再 CSRedisClient Dispose 的时候才会出现，另外在以下事件也会触发。

AppDomain.CurrentDomain.ProcessExit += (s1, e1) =>
            {
                running = false;
            };
            Console.CancelKeyPress += (s1, e1) =>
            {
                running = false;
            };


确保 CSRedisClient 单例定义。

**Comment by rteam** [comment]
在Startup的ConfigureServices中调用了一次RedisHelper.Initialization(new CSRedis.CSRedisClient(this.Configuration["SimpleCache:Redis"]));

ioc用的是autofac

缓存管理器注册：

`            builder.RegisterType<SimpleRedisCacheManager<IList<CourseGradeValue>>>().As<ISimpleCacheManager<IList<CourseGradeValue>>>().WithParameter("SettingKey", "HotCache").SingleInstance();
            builder.RegisterType<SimpleRedisCacheManager<IList<FormativeTestValue>>>().As<ISimpleCacheManager<IList<FormativeTestValue>>>().WithParameter("SettingKey", "HotCache").SingleInstance();
            builder.RegisterType<SimpleRedisCacheManager<IList<StudentCourseBehaviorValue>>>().As<ISimpleCacheManager<IList<StudentCourseBehaviorValue>>>().WithParameter("SettingKey", "HotCache").SingleInstance();
            builder.RegisterType<SimpleRedisCacheManager<IList<StudentRankValue>>>().As<ISimpleCacheManager<IList<StudentRankValue>>>().WithParameter("SettingKey", "HotCache").SingleInstance();
            builder.RegisterType<SimpleRedisCacheManager<IList<ClassCourseRankValue>>>().As<ISimpleCacheManager<IList<ClassCourseRankValue>>>().WithParameter("SettingKey", "HotCache").SingleInstance();
            builder.RegisterType<SimpleRedisCacheManager<LearningArchivesValue>>().As<ISimpleCacheManager<LearningArchivesValue>>().WithParameter("SettingKey", "HotCache").SingleInstance();`

管理器实现：

`public class SimpleRedisCacheManager<TCacheValue> : ISimpleCacheManager<TCacheValue>
    {
        public SimpleRedisCacheManager(string SettingKey, IOptions<SimpleCacheOption> Option)
        {
            this.Key = SettingKey;
            this.Option = Option.Value;
            this.Setting = Option.Value.Settings.SingleOrDefault(t => t.Key.Equals(SettingKey, StringComparison.OrdinalIgnoreCase));
        }

        /// <summary>
        /// 设置
        /// </summary>
        protected SimpleCacheSetting Setting { get; set; }

        protected string Key { get; set; }

        public virtual SimpleCacheOption Option { get; protected set; }

        /// <summary>
        /// 添加或更新
        /// </summary>
        /// <param name="Key">缓存Key</param>
        /// <param name="cacheValue">要缓存的对象</param>
        /// <returns></returns>
        public virtual bool AddOrUpdate(string Key, TCacheValue cacheValue)
        {
            if (Key.IsEmpty())
                throw new ArgumentNullException(nameof(Key));

            if (cacheValue == null)
                throw new ArgumentNullException(nameof(cacheValue));

            return RedisHelper.Set(Key, cacheValue, this.Setting.ExpiresTime);
        }

        /// <summary>
        /// 缓存是否存在
        /// </summary>
        /// <param name="Key">缓存Key</param>
        /// <returns></returns>
        public virtual bool Exist(string Key)
        {
            return RedisHelper.Exists(Key);
        }

        /// <summary>
        /// 删除指定缓存项
        /// </summary>
        /// <param name="Key">缓存Key</param>
        /// <returns></returns>
        public virtual bool Remove(string Key)
        {
            return RedisHelper.Del(Key) > 0 ? true : false;
        }

        /// <summary>
        /// 获取或添加缓存
        /// </summary>
        /// <param name="Key">缓存Key</param>
        /// <param name="valueFactory">缓存对象工厂</param>
        /// <returns></returns>
        public virtual async Task<TCacheValue> GetOrAddAsync(string Key, Func<string, Task<TCacheValue>> valueFactory)
        {
            if (Key.IsEmpty())
                throw new ArgumentNullException(nameof(Key));

            if (valueFactory == null)
                throw new ArgumentNullException(nameof(valueFactory));

            TCacheValue value = RedisHelper.Get<TCacheValue>(Key);
            if (value != null)
                return value;

            value = await valueFactory(Key).ConfigureAwait(false);
            if (value == null)
                return default(TCacheValue);

            if (RedisHelper.Set(Key, value, this.Setting.ExpiresTime))
                return value;

            return default(TCacheValue);
        }

        /// <summary>
        /// 获取或添加缓存
        /// </summary>
        /// <param name="Key">缓存Key</param>
        /// <param name="valueFactory">缓存对象工厂</param>
        /// <param name="value">取出的缓存值</param>
        /// <returns></returns>
        public virtual bool TryGetOrAdd(string Key, Func<string, TCacheValue> valueFactory, out TCacheValue value)
        {
            if (Key.IsEmpty())
                throw new ArgumentNullException(nameof(Key));

            if (valueFactory == null)
                throw new ArgumentNullException(nameof(valueFactory));

            value = RedisHelper.Get<TCacheValue>(Key);
            if (value != null)
                return true;

            value = valueFactory(Key);
            if (value == null)
                return false;

            if (RedisHelper.Set(Key, value, this.Setting.ExpiresTime))
            {
                return true;
            }

            value = default(TCacheValue);
            return false;
        }
    }`

用的时候直接在构造函数注入，比如：

ISimpleCacheManager<LearningArchivesValue> LearningArchivesCacheManager

看起来是单例模式呀


AppDomain.CurrentDomain.ProcessExit += (s1, e1) =>
{
running = false;
};
Console.CancelKeyPress += (s1, e1) =>
{
running = false;
};

这个事件我并没有用

**Comment by 2881099** [comment]
是集群，或哨兵？

**Comment by 2881099** [comment]
https://github.com/2881099/SafeObjectPool/blob/master/SafeObjectPool/ObjectPool.cs

279 行抛出的异常，集群或哨兵因为切换节点，切换过程中有可能报这个村。还有就是上面的情况，CSRedis Dispose 或者 上面提到的两事件。

**Comment by rteam** [comment]
华为云的Cluster集群，3节点，没有用哨兵模式，缓存就是用单例模式，请问如果是因为集群引起的如何规避？是否有相关设置？谢谢。

**Comment by 2881099** [comment]
testcluster=false这个参数加了吗？不太清楚华为云，是否和阿里腾讯云一样，腾讯云阿里云集群要用这个参数，使用起来和单机版redis没区别。频道切换节点貌似也有问题，毕竟你只有三节点，为啥会一直操错

**Comment by rteam** [comment]
我试试看，华为云在前端提供了一个域名，通过这个域名访问集群，并不是多个ip

**Comment by rteam** [comment]
![image](https://user-images.githubusercontent.com/914239/67644687-aad77600-f95e-11e9-9db1-0192391e6218.png)
没有效果，华为云的集群是上图这个架构，版本是5.0

**Comment by 2881099** [comment]
这些节点是固定的吗，集群初始化的时候会得到所有节点和slot缓存信息，以后常驻内存中，没理由会在运行中不断的出新的节点啊。是测试服还是正式服，我可以测试吗？

SimpleCache:Redis 这个配置发一下吗，去掉密码配置发。

**Comment by rteam** [comment]
应该是固定的，是正式服，只能内网访问，不过我可以建一个虚拟机和新实例给你测试，能留个邮箱吗？
{
  "SimpleCache": {
    "Redis": "redis-7a877a4-dcs-hijn.dcs.huaweicloud.com:6379,allowAdmin=true,abortConnect=false,password=,testcluster=false",
    "Settings": [
      {
        "Key": "FastCache",
        "ExpiresTime": 180
      },
      {
        "Key": "HotCache",
        "ExpiresTime": 1800
      },
      {
        "Key": "HistoryCache",
        "ExpiresTime": 86400
      },
      {
        "Key": "LongCache",
        "ExpiresTime": 604800
      }
    ]
  }
}

**Comment by 2881099** [comment]
2881099@qq.com 测试代码也附上一份

**Comment by rteam** [comment]
不好意思，查到原因了，不是csredis的事情，是数据库mongodb出故障了

**Comment by netkey** [comment]
> 不好意思，查到原因了，不是csredis的事情，是数据库mongodb出故障了

能分享下是啥原因吗？我们也遇到类似情况了。k8s集群中发布应用的时候遇到这个问题，应用也同时连接redis和mongodb，检查redis和mongodb没有发现有什么异常。

Object name: '【192.168.3.10:6379/0】对象池已释放，无法访问。'."}

{"Level":"Error","Time":"2019-12-19 18:56:27.276","Method":"全局异常:","Param":"System.TimeoutException: A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "Automatic", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "192.168.3.10:27017" }", EndPoint: "192.168.3.10:27017", State: "Disconnected", Type: "Unknown" }] }.

**Comment by 2881099** [comment]
> > 不好意思，查到原因了，不是csredis的事情，是数据库mongodb出故障了
> 
> 能分享下是啥原因吗？我们也遇到类似情况了。k8s集群中发布应用的时候遇到这个问题，应用也同时连接redis和mongodb，检查redis和mongodb没有发现有什么异常。
> 
> 这是部分应用的日志：
> Object name: '【192.168.3.10:6379/0】对象池已释放，无法访问。'."}
> 
> {"Level":"Error","Time":"2019-12-19 18:56:27.276","Method":"全局异常:","Param":"System.TimeoutException: A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "Automatic", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "192.168.3.10:27017" }", EndPoint: "192.168.3.10:27017", State: "Disconnected", Type: "Unknown" }] }.

AppDomain.CurrentDomain.ProcessExit += (s1, e1) =>
{
running = false;
};
Console.CancelKeyPress += (s1, e1) =>
{
running = false;
};
检查这两个事件，看会不会触发

**Comment by netkey** [comment]
我的Redis的ConnectionString的配置如下：192.168.3.10:6379,password=XXXXXX,poolsize=50
看readme默认会预热连接，默认预热的数量是和poolsize的数量相同吗？在配置中设置preheat和idleTimeout是否会有帮助？

**Comment by 2881099** [comment]
是的，preheat=false 就不预热，idleTimeout 和 redis-server 主动断开连接有关，正式环境推荐设置值 30000，即30秒。。。可以防止服务器主动断开连接，导致报错

> 另外，我们的.net core应用在发布到k8s中的时候，在应用启动较长一段时间才能开始提供服务，感觉卡在初始化redis和mongod等过程中，如果是直接通过docker容器发布的话有访问量进入到容器可能会导致应用假死状态。
> 我的Redis的ConnectionString的配置如下：192.168.3.10:6379,password=XXXXXX,poolsize=50
> 看readme默认会预热连接，默认预热的数量是和poolsize的数量相同吗？在配置中设置preheat和idleTimeout是否会有帮助？
