### ISSUE TITLE
Unexpected end of stream; expected type 'Bulk'

### ISSUE THREAD

**Issue by hero7kira** [2881099/csredis#20]
在实际使用中会经常性抛出Unexpected end of stream; expected type 'Bulk'异常和System.NotSupportedException异常，在压测时会周期性抛连接被重置异常，造成整个redis一直不可用，过一会又自己好了，使用的是单例模式，连接64个。

**Comment by hero7kira** [comment]
Message:Unexpected end of stream; expected type 'Bulk'
at CSRedis.Internal.IO.RedisReader.ExpectType(RedisMessage expectedType)
   at CSRedis.Internal.IO.RedisReader.ReadBulkBytes(Boolean checkType)
   at CSRedis.Internal.IO.RedisReader.ReadBulkString(Boolean checkType)
   at CSRedis.Internal.Commands.RedisString.Parse(RedisReader reader)
   at CSRedis.Internal.IO.RedisAsyncCommandToken`1.SetResult(RedisReader reader)
   at CSRedis.Internal.IO.AsyncConnector.OnSocketSent(SocketAsyncEventArgs args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CSRedis.CSRedisClient.<ExecuteScalarAsync>d__82`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CSRedis.CSRedisClient.<GetAsync>d__87.MoveNext()

Message:Unexpected response type: 52 (expecting Bulk)
at CSRedis.Internal.IO.RedisReader.ExpectType(RedisMessage expectedType)
   at CSRedis.Internal.IO.RedisReader.ReadBulkBytes(Boolean checkType)
   at CSRedis.Internal.IO.RedisReader.ReadBulkString(Boolean checkType)
   at CSRedis.Internal.Commands.RedisString.Parse(RedisReader reader)
   at CSRedis.Internal.IO.RedisAsyncCommandToken`1.SetResult(RedisReader reader)
   at CSRedis.Internal.IO.AsyncConnector.OnSocketSent(SocketAsyncEventArgs args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CSRedis.CSRedisClient.<ExecuteScalarAsync>d__82`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CSRedis.CSRedisClient.<GetAsync>d__87.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Open.SchoolBase.Redis.RedisClient.<GetAsync>d__22`1.MoveNext()

上面是日志，由于异常数量太大，没有挨个查看，最多的是Get和GetAsync，最后抛异常的都是ExpectType这个方法，本地测试时没有发现这个问题，发到线上开始也没有问题，过一段时间后会出现这个问题。

还有就是System.NotSupportedException异常：
Message:Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream.

at System.IO.BufferedStream.ClearReadBufferBeforeWrite()
   at System.IO.BufferedStream.Write(Byte[] array, Int32 offset, Int32 count)
   at CSRedis.Internal.IO.RedisWriter.Write(RedisCommand command, Stream stream)
   at CSRedis.Internal.RedisConnector.Call[T](RedisCommand`1 command)
   at CSRedis.RedisClient.Write[T](RedisCommand`1 command)
   at CSRedis.RedisClient.Expire(String key, TimeSpan expiration)
   at CSRedis.CSRedisClient.<>c__DisplayClass22_0.<Expire>b__0(RedisClient c, String k)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Expire(String key, TimeSpan expire)

最后那个连接被重置异常，日志被清掉了，我粗略看了下源码，感觉是没有跟服务端保持心跳，被服务端关掉了

**Comment by 2881099** [comment]
有可能是服务端断开连接了，使用两年多部署过 centos/debian/ubuntu 127.0.0.1访问，没发现这个问题

我追问下

1、Get GetAsync 内容多大，是 byte[] 还是 string
2、服务器环境，远程操作还是127.0.0.1

**Comment by hero7kira** [comment]
1.最大的String内容279813 bytes，所有内容string存储,
2.ubuntu14.04 远程操作
3.redis timeout 配置为60s

**Comment by hero7kira** [comment]
兄弟你qq多少，咱详细聊呗

**Comment by 2881099** [comment]
2881099

**Comment by hero7kira** [comment]
问题找到了，主要是由于没有跟服务器进行心跳通信，所以如果redis服务端配置了timeout属性，在这个时间段内没有进行通信，连接会被redis关闭，但是驱动内部的IsConnected属性还是true，所以使用连接发送命令时会抛出异常，解决方案配置redis的timeout属性为0,或者增加心跳通信或连接存活检测
