### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by wanghaoxing** [2881099/csredis#201]
```
Unhandled Exception: System.Net.Sockets.SocketException: Address already in use
at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
at CSRedis.CSRedisClient.LPop(String key)
at RedisHelper`1.LPop(String key)
```
使用csredis会报上面异常

**Comment by 2881099** [comment]
客户端也报这个错误，没见过。可能是环境问题

**Comment by wanghaoxing** [comment]
```
【localhost:6379/0】状态不可用，等待后台检查程序恢复方可使用。Connection was not opened- 堆栈信息   at SafeObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
         at SafeObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
         at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
         at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
         at CSRedis.CSRedisClient.LPop(String key)
         at RedisHelper`1.LPop(String key)
```
我连本地的调试会报这个错

**Comment by 2881099** [comment]
连接串发出来看下

**Comment by wanghaoxing** [comment]
```
localhost,prefix=v3test,writeBuffer=10240,tryit=3,idleTimeout=20,poolsize=500,preheat=50
```

**Comment by 2881099** [comment]
idleTimeout 这个设置去掉试试

**Comment by 2881099** [comment]
而且值应该是毫秒

**Comment by wanghaoxing** [comment]
去掉暂时压测了一下,目前没看到异常,不过当时加这个配置是
```
`【172.16.0.146:6379/0】：Unable to read data from the transport connection: Connection timed out. at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func2 handler, Int32 jump, Int32 errtimes) at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func3 hander) at CSRedis.CSRedisClient.LPop(String key) at RedisHelper`1.LPop(String key)，会卡住，几十秒才处理一条还会丢数据。 作者建议，idleTimeout 调一下，大于5秒，小于服务器设置断开的时间，我设置成了20`
```
我查看了下笔记是因为上面原因..谢谢了,我再观察下

**Comment by 2881099** [comment]
单位是毫秒，设置成20相当于0.02秒。

5秒应该设置成5000
