### ISSUE TITLE
Connection was not opened

### ISSUE THREAD

**Issue by IrvingLu** [2881099/csredis#219]
作者你好
我们这里突然发现了“Connection was not opened”的报错，之前一直没有大量的使用所以没有发现，我们的redis是阿里云的主从模式服务器，所以没有设置testcluster=false，查了一些资料还是没有解决，请帮忙看一下。
连接字符是：xxx.redistest.com:16379,ssl=False,password=test,poolsize=30,preheat=false,writeBuffer=20480,idleTimeout=20000,tryit=2
下面是详细的报错信息：
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Exists(String key)
   at RedisHelper`1.Exists(String key)
   at JD.Core.Caching.CsRedisHelper.Get[T](String key, Func`1 acquire) in /var/lib/jenkins/workspace/JD.Web_127/JDMicroService/JD.Core/Caching/CsRedisHelper.cs:line 25
   at JD.Services.Web.HomePageService.GetHomePage() in /var/lib/jenkins/workspace/JD.Web_127/JDMicroService/JD.Services/Web/HomePageService.cs:line 47
   at JD.Web.Controllers.Web.JdHomeController.GetHomePage() in /var/lib/jenkins/workspace/JD.Web_127/JDMicroService/JD.Web/Controllers/Web/JdHomeController.cs:line 45
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)

**Comment by 2881099** [comment]
xxx.redistest.com:16379,ssl=False,password=test,poolsize=30,preheat=5,idleTimeout=20000,writeBuffer=20480,idleTimeout=20000,tryit=2

用这个试试

**Comment by 2881099** [comment]
idleTimeout=20000

20秒不活跃，则销毁旧连接，创建新连接。

有的服务器会自动断开不活跃的连接，所以加这个参数可以解决。

**Comment by IrvingLu** [comment]
改了之后出了新的报错了
Unexpected end of stream; expected type 'Int'; data = ''
上次出了这个问题，加了“idleTimeout=20000,tryit=2”就好了，还要修改别的东西吗？

**Comment by 2881099** [comment]
Unexpected end of stream; expected type 'Int'; data = ''

这个错误现在还在吗？StackTract 发出来看下

**Comment by IrvingLu** [comment]
at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Exists(String key)
   at RedisHelper`1.Exists(String key)
   at JD.Core.Caching.CsRedisHelper.Get[T](String key, Func`1 acquire) in /var/lib/jenkins/workspace/JD.Web_127/JDMicroService/JD.Core/Caching/CsRedisHelper.cs:line 25
   at JD.Services.Web.HomePageService.GetHomePage() in /var/lib/jenkins/workspace/JD.Web_127/JDMicroService/JD.Services/Web/HomePageService.cs:line 47
   at JD.Web.Controllers.Web.JdHomeController.GetHomePage() in /var/lib/jenkins/workspace/JD.Web_127/JDMicroService/JD.Web/Controllers/Web/JdHomeController.cs:line 45
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)

**Comment by 2881099** [comment]
Exists 只有这个命令出错吗，其他的有没

**Comment by IrvingLu** [comment]
没有了 我感觉还是连接一直没有释放 上午加了"preheat=5"之后 连接数一直在上升
![image](https://user-images.githubusercontent.com/26640655/70414532-55ca6c00-1a95-11ea-9781-a4953ce78866.png)

**Comment by 2881099** [comment]
CSRedisClient 创建了多少次啊，搜索下 new CSRedisClient

**Comment by IrvingLu** [comment]
我确实使用了好多次，原来一次创建就是一个连接，我改一下再看看，多谢了。

**Comment by 2881099** [comment]
整个程序只创建一次，用 static 保存起来

poolsize=500,preheat=10

**Comment by IrvingLu** [comment]
好的 我试试

**Comment by IrvingLu** [comment]
解决了
