### ISSUE TITLE
状态不可用，等待后台检查程序恢复方可使用

### ISSUE THREAD

**Issue by JimHuang9** [2881099/csredis#232]
您好：我的连接串是:ip:6379,idleTimeout=4500,版本3.1.8,请问这是什么情况？
System.Exception: 【ip:6379/0】状态不可用，等待后台检查程序恢复方可使用。Object reference not set to an instance of an object.
   at SafeObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
   at SafeObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Set(String key, Object value, Int32 expireSeconds, Nullable`1 exists)
   at RedisHelper`1.Set(String key, Object value, Int32 expireSeconds, Nullable`1 exists)

**Comment by 2881099** [comment]
升个级看看 v3.3.0

idleTimeout=15000

最好设置 > 5 秒

**Comment by JimHuang9** [comment]
好,我调整后再观察看看,谢谢
