### ISSUE TITLE
正在实施引入到 CO2NET 和 Senparc.Weixin SDK，希望作者能多支持和指点！

### ISSUE THREAD

**Issue by JeffreySu** [2881099/csredis#247]
计划将使用csredis用于取代StackExchange.Redis，目前会在以下两个安装量比较大的项目开始：
https://github.com/Senparc/Senparc.CO2NET
https://github.com/JeffreySu/WeiXinMPSDK

预计两周内出正式版，如有问题我会追加到下面，希望作者多支持！谢谢！

**Comment by 2881099** [comment]
谢谢苏总的支持，建议可以将redis连接串直接交给使用者配置，使用者根据环境调优。

**Comment by JeffreySu** [comment]
嗯，我们目前是放在Web.config或appsettings.json下面，我今天先出一个preview。 👍

**Comment by JeffreySu** [comment]
@2881099  看了这里有两个锁：https://github.com/2881099/csredis/issues/246

现在我这边有一个同步锁需要改造，不知道应该使用哪个取代，或者都不是？https://github.com/Senparc/Senparc.CO2NET/blob/68883207fb4d077e0333c1a0345219b372aeae26/src/Senparc.CO2NET.Cache.Redis.RedLock/redlock-cs/src/Redlock.cs#L46

注：这里的Redlock用了redis官方推荐的同步锁算法。

**Comment by 2881099** [comment]
@JeffreySu RedisHelper.Lock 是普通锁的封装，单机版 redis 够用。

Redlock 需要另外实现，解决主从复制 master/salve 切换瞬间的问题。

Redlock.cs 的代码可以替换成 CSRedisClient 对应的方法

**Comment by 2881099** [comment]
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Redlock.CSharp
{
    public class Lock
    {

        public Lock(string resource, byte[] val, TimeSpan validity)
        {
            this.resource = resource;
            this.val = val ;
            this.validity_time = validity;
        }

        private string resource;

        private byte[] val;

        private TimeSpan validity_time;

        public string Resource { get { return resource; } }

        public byte[] Value { get { return val; } }

        public TimeSpan Validity { get { return validity_time; } }
    }
}

using CSRedis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace Redlock.CSharp
{
    public class Redlock
    {
        public Redlock(int retryCount, TimeSpan retryDelay, params CSRedisClient[] list)
        {
            DefaultRetryCount = retryCount;
            DefaultRetryDelay = retryDelay;
            foreach (var item in list)
            {
                this.redisMasterDictionary.Add(item.Nodes.Keys.First(), item);
            }
        }

        public Redlock(params CSRedisClient[] list)
            : this(3, new TimeSpan(0, 0, 0, 0, 200), list)
        {

        }

        readonly int DefaultRetryCount = 3;
        readonly TimeSpan DefaultRetryDelay = new TimeSpan(0, 0, 0, 0, 200);
        const double ClockDriveFactor = 0.01;

        protected int Quorum { get { return (redisMasterDictionary.Count / 2) + 1; } }

        /// <summary>
        /// String containing the Lua unlock script.
        /// </summary>
        const String UnlockScript = @"
            if redis.call(""get"",KEYS[1]) == ARGV[1] then
                return redis.call(""del"",KEYS[1])
            else
                return 0
            end";


        protected static byte[] CreateUniqueLockId()
        {
            return Guid.NewGuid().ToByteArray();
        }


        protected Dictionary<String, CSRedisClient> redisMasterDictionary = new Dictionary<string, CSRedisClient>();

        #region 同步方法

        //TODO: Refactor passing a ConnectionMultiplexer
        protected bool LockInstance(string redisServer, string resource, byte[] val, TimeSpan ttl)
        {

            bool succeeded;
            try
            {
                var redis = this.redisMasterDictionary[redisServer];
                succeeded = redis.Set(resource, val, ttl, RedisExistence.Nx);
            }
            catch (Exception)
            {
                succeeded = false;
            }
            return succeeded;
        }

        //TODO: Refactor passing a ConnectionMultiplexer
        protected void UnlockInstance(string redisServer, string resource, byte[] val)
        {
            string key = resource;
            byte[][] values = { val };
            var redis = redisMasterDictionary[redisServer];
            redis.Eval(
                UnlockScript,
                key,
                values
                );
        }

        public bool Lock(string resource, TimeSpan ttl, out Lock lockObject)
        {
            var val = CreateUniqueLockId();
            Lock innerLock = null;
            bool successfull = retry(DefaultRetryCount, DefaultRetryDelay, () =>
            {
                try
                {
                    int n = 0;
                    var startTime = DateTime.Now;

                    // Use keys
                    for_each_redis_registered(
                        redis =>
                        {
                            if (LockInstance(redis, resource, val, ttl)) n += 1;
                        }
                    );

                    /*
                     * Add 2 milliseconds to the drift to account for Redis expires
                     * precision, which is 1 millisecond, plus 1 millisecond min drift 
                     * for small TTLs.        
                     */
                    var drift = Convert.ToInt32((ttl.TotalMilliseconds * ClockDriveFactor) + 2);
                    var validity_time = ttl - (DateTime.Now - startTime) - new TimeSpan(0, 0, 0, 0, drift);

                    if (n >= Quorum && validity_time.TotalMilliseconds > 0)
                    {
                        innerLock = new Lock(resource, val, validity_time);
                        return true;
                    }
                    else
                    {
                        for_each_redis_registered(
                            redis =>
                            {
                                UnlockInstance(redis, resource, val);
                            }
                        );
                        return false;
                    }
                }
                catch (Exception)
                { return false; }
            });

            lockObject = innerLock;
            return successfull;
        }

        protected void for_each_redis_registered(Action<CSRedisClient> action)
        {
            foreach (var item in redisMasterDictionary)
            {
                action(item.Value);
            }
        }

        protected void for_each_redis_registered(Action<String> action)
        {
            foreach (var item in redisMasterDictionary)
            {
                action(item.Key);
            }
        }

        protected bool retry(int retryCount, TimeSpan retryDelay, Func<bool> action)
        {
            int maxRetryDelay = (int)retryDelay.TotalMilliseconds;
            Random rnd = new Random();
            int currentRetry = 0;

            while (currentRetry++ < retryCount)
            {
                if (action()) return true;
                Thread.Sleep(rnd.Next(maxRetryDelay));
            }
            return false;
        }

        public void Unlock(Lock lockObject)
        {
            for_each_redis_registered(redis =>
                {
                    UnlockInstance(redis, lockObject.Resource, lockObject.Value);
                });
        }

        #endregion

        #region 异步方法

        //TODO: Refactor passing a ConnectionMultiplexer
        protected async Task<bool> LockInstanceAsync(string redisServer, string resource, byte[] val, TimeSpan ttl)
        {

            bool succeeded;
            try
            {
                var redis = this.redisMasterDictionary[redisServer];
                succeeded = await redis.SetAsync(resource, val, ttl, RedisExistence.Nx).ConfigureAwait(false);
            }
            catch (Exception)
            {
                succeeded = false;
            }
            return succeeded;
        }

        //TODO: Refactor passing a ConnectionMultiplexer
        protected async Task UnlockInstanceAsync(string redisServer, string resource, byte[] val)
        {
            string key = resource;
            byte[][] values = { val };
            var redis = redisMasterDictionary[redisServer];
            await redis.EvalAsync(
                   UnlockScript,
                   key,
                   values
                   ).ConfigureAwait(false);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="resource"></param>
        /// <param name="ttl"></param>
        /// <returns>bool：successfull，Lock：lockObject</returns>
        public async Task<Tuple<bool, Lock>> LockAsync(string resource, TimeSpan ttl)
        {
            var val = CreateUniqueLockId();
            Lock innerLock = null;
            bool successfull = await retryAsync(DefaultRetryCount, DefaultRetryDelay, async () =>
              {
                  try
                  {
                      int n = 0;
                      var startTime = DateTime.Now;

                      // Use keys
                       for_each_redis_registered(
                             async redis =>
                              {
                                  if (await LockInstanceAsync(redis, resource, val, ttl).ConfigureAwait(false)) n += 1;
                              }
                          );

                      /*
                       * Add 2 milliseconds to the drift to account for Redis expires
                       * precision, which is 1 millisecond, plus 1 millisecond min drift 
                       * for small TTLs.        
                       */
                      var drift = Convert.ToInt32((ttl.TotalMilliseconds * ClockDriveFactor) + 2);
                      var validity_time = ttl - (DateTime.Now - startTime) - new TimeSpan(0, 0, 0, 0, drift);

                      if (n >= Quorum && validity_time.TotalMilliseconds > 0)
                      {
                          innerLock = new Lock(resource, val, validity_time);
                          return true;
                      }
                      else
                      {
                          for_each_redis_registered(
                               async redis =>
                                {
                                    await UnlockInstanceAsync(redis, resource, val).ConfigureAwait(false);
                                }
                            );
                          return false;
                      }
                  }
                  catch (Exception)
                  { return false; }
              }).ConfigureAwait(false);

            return Tuple.Create(successfull, innerLock);
        }

        protected async Task for_each_redis_registeredAsync(Action<CSRedisClient> action)
        {
            await Task.Factory.StartNew(() => for_each_redis_registered(action)).ConfigureAwait(false);
        }

        protected async Task for_each_redis_registeredAsync(Action<String> action)
        {
            await Task.Factory.StartNew(() => for_each_redis_registered(action)).ConfigureAwait(false);

        }

        protected async Task<bool> retryAsync(int retryCount, TimeSpan retryDelay, Func<Task<bool>> action)
        {
            int maxRetryDelay = (int)retryDelay.TotalMilliseconds;
            Random rnd = new Random();
            int currentRetry = 0;

            while (currentRetry++ < retryCount)
            {
                if (await action().ConfigureAwait(false)) return true;
                Thread.Sleep(rnd.Next(maxRetryDelay));
            }
            return false;
        }

        public async Task UnlockAsync(Lock lockObject)
        {
            await for_each_redis_registeredAsync(async redis =>
             {
                 await UnlockInstanceAsync(redis, lockObject.Resource, lockObject.Value).ConfigureAwait(false);
             }).ConfigureAwait(false);
        }

        #endregion

        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine(this.GetType().FullName);

            sb.AppendLine("Registered Connections:");
            foreach (var item in redisMasterDictionary)
            {
                sb.AppendLine(item.Key.First().ToString());
            }

            return sb.ToString();
        }
    }
}
```

刚才试着改了一下，可以编译通过

**Comment by 2881099** [comment]
```csharp
        public override ICacheLock Lock()
        {
            if (_retryCount != 0)
            {
                _dlm = new Redlock.CSharp.Redlock(_retryCount, _retryDelay, _redisStrategy.Client);
            }
            else if (_dlm == null)
            {
                _dlm = new Redlock.CSharp.Redlock(_redisStrategy.Client);
            }

            var ttl = base.GetTotalTtl(_retryCount, _retryDelay);
            base.LockSuccessful = _dlm.Lock(_resourceName, TimeSpan.FromMilliseconds(ttl), out _lockObject);
            return this;
        }
```

@JeffreySu 我看到 Senparc.CO2NET.Cache.Redis 类定调用的时候，也只传了一个 ConnectionMultiplexer 对像进来，这样调用是否没使用到 Redlock 的特点？

**Comment by JeffreySu** [comment]
@2881099 您是说支持使用哨兵或者主从之类的特点吗？

**Comment by 2881099** [comment]
@JeffreySu  是的，RedisHelper.Lock 多数情况下够用。

**Comment by 2881099** [comment]
@JeffreySu 
ConnectionMultiplexer 和 CSRedisClient 类型对应，都是单例定义。

方法名 CSRedisClient 和 redis 命令95%相同。

**Comment by JeffreySu** [comment]
https://github.com/Senparc/Senparc.CO2NET/blob/0044841287c7ae93fba241b66d85f18d11de7d1f/src/Senparc.CO2NET.Cache.CsRedis/ObjectCacheStrategy/RedisObjectCacheStrategy.cs#L352

Client.Keys() 方法下面，是不是缺少一个指定database的参数？只有一个pattern参数。另外如果有pageSize这个参数很多情况下也挺实用的。

之前用 ConnectionMultiplexer  可以使用Client.GetDatabase().Database获得：

https://github.com/Senparc/Senparc.CO2NET/blob/a9c0bc321f6afdbdac36c52fb0e32e52ae8cfea3/src/Senparc.CO2NET.Cache.Redis/ObjectCacheStrategy/RedisObjectCacheStrategy.cs#L183

**Comment by 2881099** [comment]
> Client.Keys() 方法下面，是不是缺少一个指定database的参数？只有一个pattern参数。另外如果有pageSize这个参数很多情况下也挺实用的。

@JeffreySu 对应 keys 或者 scan ，db 在连接串上设置的，中途使用中切换不了。

**Comment by 2881099** [comment]
var csredis = new CSRedis.CSRedisClient("127.0.0.1:6379,password=123,defaultDatabase=13");

**Comment by JeffreySu** [comment]
另外一个问题，如果要判断Key是否存在（KeyExists），推荐用哪个方法？

**Comment by 2881099** [comment]
@JeffreySu KeyExists 应该对应 exists 命令

这里有 redis 命令中文文档 http://redisdoc.com/

CSRedisClient 方法名和这里几乎一样

**Comment by JeffreySu** [comment]
> @JeffreySu KeyExists 应该对应 exists 命令
> 
> 这里有 redis 命令中文文档 http://redisdoc.com/
> 
> CSRedisClient 方法名和这里几乎一样

好嘞 👍

**Comment by JeffreySu** [comment]
![image](https://user-images.githubusercontent.com/2281927/73669333-3c831c00-46e2-11ea-8157-afcd106d0c4f.png)

目前通过一个简单的同步方法运行效率单元测试，反复测试之后的结果是：
当前类库存取效率大致是 StackExchange.Redis 的两倍左右 🥇 

https://github.com/Senparc/Senparc.CO2NET/blob/9e4bd2a5e96c03dc33d7df87486f13011b44af5f/src/Senparc.CO2NET.Cache.CsRedis.Tests/RedisTest.cs#L138

**Comment by JeffreySu** [comment]
已发布 CsRedis 版本，感谢 @2881099 !

**Comment by 2881099** [comment]
苏总效率真高，谢谢

**Comment by JeffreySu** [comment]
@2881099 今天看日志碰到了两个以前不会出现的错误，一般是什么原因呢？

1.

ExecptionMessage:Unable to read data from the transport connection: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.
CSRedisCore
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Set(String key, Object value, Int32 expireSeconds, Nullable`1 exists)
   at Senparc.CO2NET.Cache.CsRedis.RedisObjectCacheStrategy.Set(String key, Object value, Nullable`1 expiry, Boolean isFullKey)
   at Senparc.NeuChar.Context.GlobalMessageContext`3.UpdateMessageContext(TMC messageContext)
   at Senparc.Weixin.MP.Sample.CommonService.CustomMessageHandler.CustomMessageHandler.OnExecutedAsync(CancellationToken cancellationToken) in d:\a\1\s\Samples\net45-mvc\Senparc.Weixin.MP.Sample.CommonService\MessageHandlers\CustomMessageHandler\Async\CustomMessageHandlerAsync.cs:line 48
   at Senparc.NeuChar.MessageHandlers.MessageHandler`3.ExecuteAsync(CancellationToken cancellationToken)
   at Senparc.NeuChar.MessageHandlers.MessageHandler`3.Execute()
   at Senparc.Weixin.Sample.NetCore3.Controllers.WeixinController.Post(PostModel postModel)
========= InnerException =========
由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
System.Net.Sockets
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)


2. 

ExecptionMessage:Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream.
CSRedisCore
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Set(String key, Object value, Int32 expireSeconds, Nullable`1 exists)
   at Senparc.CO2NET.Cache.CsRedis.RedisObjectCacheStrategy.Set(String key, Object value, Nullable`1 expiry, Boolean isFullKey)
   at Senparc.NeuChar.Context.GlobalMessageContext`3.UpdateMessageContext(TMC messageContext)
   at Senparc.Weixin.MP.Sample.CommonService.CustomMessageHandler.CustomMessageHandler.OnExecutedAsync(CancellationToken cancellationToken) in d:\a\1\s\Samples\net45-mvc\Senparc.Weixin.MP.Sample.CommonService\MessageHandlers\CustomMessageHandler\Async\CustomMessageHandlerAsync.cs:line 46
   at Senparc.NeuChar.MessageHandlers.MessageHandler`3.ExecuteAsync(CancellationToken cancellationToken)
   at Senparc.NeuChar.MessageHandlers.MessageHandler`3.Execute()
   at Senparc.Weixin.Sample.NetCore3.Controllers.WeixinController.Post(PostModel postModel) in d:\a\1\s\Samples\netcore3.0-mvc\Senparc.Weixin.Sample.NetCore3\Controllers\WeixinController.cs:line 126

**Comment by 2881099** [comment]
可能是长时间不活跃，连接被服务端回收。

连接串增加配置 idletimeout=15000

**Comment by JeffreySu** [comment]
还发现了一个异常提示： `发送数据长度 10271 大于 异步写入缓冲块大小 10240，请设置连接串参数：writeBuffer` 哪里还需要单独配置吗？用的代码和之前 StackExchange.Redis 是一样的。

**Comment by 2881099** [comment]
> 还发现了一个异常提示： `发送数据长度 10271 大于 异步写入缓冲块大小 10240，请设置连接串参数：writeBuffer` 哪里还需要单独配置吗？用的代码和之前 StackExchange.Redis 是一样的。

这个问题确实存在，最近改过异步内部实现，还没有发布。

用同步方法没这个限制。

**Comment by 2881099** [comment]
写入数据过大的时候，发生的错误。

**Comment by JeffreySu** [comment]
大概什么时候能发布？我们模块里面已经全面异步了，现在有几个项目都已经上CSRedis了，也都是尽量用异步方法。

**Comment by JeffreySu** [comment]
> 可能是长时间不活跃，连接被服务端回收。
> 
> 连接串增加配置 idletimeout=15000

这个问题和模块的连接方式有关吗？之前运行好几年都没有出过这个问题，Redis服务应该是稳定的。

**Comment by 2881099** [comment]
> > 可能是长时间不活跃，连接被服务端回收。
> > 连接串增加配置 idletimeout=15000
> 
> 这个问题和模块的连接方式有关吗？之前运行好几年都没有出过这个问题，Redis服务应该是稳定的。

这个情况，和navicat连接远程数据库，一段时间不活跃再操作，卡住很久提示：服务器没响应。

stackexchange.redis 有心跳包保持会话，因为单简介模式，心跳包好做。

csredis 用的连接池，心跳包运行成本过高，所以才用过期策略实现的，默认是永不过期。idletimeout 参数是过期时间，每次使用连接的时候判断，最后活跃时间大于此值的时候使用新连接，旧连接释放。

**Comment by 2881099** [comment]
> 还发现了一个异常提示： `发送数据长度 10271 大于 异步写入缓冲块大小 10240，请设置连接串参数：writeBuffer` 哪里还需要单独配置吗？用的代码和之前 StackExchange.Redis 是一样的。

之前使用的 SocketAsyncEventArgs 没处理好这个，去年一直在忙着 FreeSql 项目。12月份已经改成了 Begin 这种传统方式，刚才已经发布了 3.4.0。

StackExchange.Redis 使用 System.IO.Pipeliens 不兼容低版本 .net framework。

**Comment by JeffreySu** [comment]
@2881099 是不是只要升级最新的版本就能解决 `发送数据长度 10271 大于 异步写入缓冲块大小 10240，请设置连接串参数：writeBuffe` 这个问题了？我们 Demo 站升级之后已经因为这个崩了好几次了。

**Comment by 2881099** [comment]
> @2881099 是不是只要升级最新的版本就能解决 `发送数据长度 10271 大于 异步写入缓冲块大小 10240，请设置连接串参数：writeBuffe` 这个问题了？我们 Demo 站升级之后已经因为这个崩了好几次了。

是的，升级可以解决这个问题
