### ISSUE TITLE
正式环境中经常出现：Unexpected response type: Status (expecting Bulk) 和 Connection was not opened

### ISSUE THREAD

**Issue by weisenzcharles** [2881099/csredis#253]
Redis：阿里云
项目框架：netcoreapp2.1
连接字符串：
![20200229143739](https://user-images.githubusercontent.com/15856772/75602517-1eea7c00-5b01-11ea-88ef-c8efcf427448.png)
存储数据为 json 格式，数据是一些试题，数据量可能比较大一般 5-20KB 左右。

**Comment by weisenzcharles** [comment]
![20200229144442](https://user-images.githubusercontent.com/15856772/75602618-09c21d00-5b02-11ea-973a-3334d803379d.png)

**Comment by 2881099** [comment]
CSRedisCore 版本是多少

**Comment by weisenzcharles** [comment]
Caching.CSRedis 3.0.13.0

**Comment by 2881099** [comment]
升级到 3.4.5

**Comment by weisenzcharles** [comment]
升级了还是有同样的问题，两台服务器，其中一台一直会随机报这个异常，另一台目前没发现这个问题
2020-02-29T16:03:00.5058039+08:00 0HLTSTI1BNB9Q:00000007 [ERR] ExceptionMiddleware.InvokeAsync (d1102078)
System.IO.EndOfStreamException: Unexpected end of stream; expected type 'Bulk'; data = ''
   at CSRedis.Internal.IO.RedisReader.ExpectType(RedisMessage expectedType)
   at CSRedis.Internal.IO.RedisReader.ReadBulkBytes(Boolean checkType)
   at CSRedis.Internal.IO.RedisReader.ReadBulkString(Boolean checkType)
   at CSRedis.Internal.Commands.RedisString.Parse(RedisReader reader)
   at CSRedis.Internal.RedisConnector.Call[T](RedisCommand`1 command)
   at CSRedis.RedisClient.Write[T](RedisCommand`1 command)
   at CSRedis.RedisClient.Get(String key)

**Comment by 2881099** [comment]
为什么你的堆栈信息没有 CSRedisClient ，而是显示的 RedisClient

**Comment by weisenzcharles** [comment]
项目着急上线，尝试了 StackExchange.Redis，目前问题已经解决。。。

**Comment by walt-liuzw** [comment]
> 项目着急上线，尝试了 StackExchange.Redis，目前问题已经解决。。。

你是换了框架了吗？换成StackExchange.Redis？

**Comment by weisenzcharles** [comment]
> > 项目着急上线，尝试了 StackExchange.Redis，目前问题已经解决。。。
> 
> 你是换了框架了吗？换成StackExchange.Redis？

是的

**Comment by waliuwangyu** [comment]
我也遇到这个原因，不过我找到问题了，就是我在修改数据的时候需要同时更新redis缓存，数据修改后我提交等待后端接口响应完成就不会出现这个错误，如果我修改了数据点击提交后我不等待后端接口响应直接刷新网页就会导致出现这个异常。总结：可能是在跟redis交互不等待响应结果导致通信异常了。
