### ISSUE TITLE
Redis的连接出现大量的CLOSE_WAIT

### ISSUE THREAD

**Issue by Yuyg77** [2881099/csredis#284]
1:线程池150  预热连接50 大概有10台服器
![image](https://user-images.githubusercontent.com/26400716/78421329-5660c100-7689-11ea-8e29-d0a58ce0106b.png)

**Comment by 2881099** [comment]
别重复 new CSRedisClient

**Comment by Yuyg77** [comment]
> 别重复 new CSRedisClient

没有重复new CSRedisClient，只是在初始化的时候，new了一次
![image](https://user-images.githubusercontent.com/26400716/78421457-662cd500-768a-11ea-89c9-e321ce5466b6.png)
![image](https://user-images.githubusercontent.com/26400716/78421464-7d6bc280-768a-11ea-9704-532120cff827.png)
项目里，大部分都这直接使用的

**Comment by Yuyg77** [comment]
按照我的使用方法，是要再加上这一句嘛？
![image](https://user-images.githubusercontent.com/26400716/78421577-42b65a00-768b-11ea-97ae-a15e1409ed85.png)

**Comment by Yuyg77** [comment]
你放，方便加你qq聊一下嘛，这个问题，现在还挺急的

**Comment by 2881099** [comment]
报版本号，运行环境，集群还是？

**Comment by Yuyg77** [comment]
> 报版本号，运行环境，集群还是？

redis版本号：3.5.5    集群   运行环境：.netcore 3.1

**Comment by 2881099** [comment]
你说的 redis 和程序怎么部署得，同机器？

CLOSE_WAIT在哪台机器出现

**Comment by Yuyg77** [comment]
> 你说的 redis 和程序怎么部署得，同机器？
> 
> CLOSE_WAIT在哪台机器出现

局域网部署的，不是同一台机器。
CLOSE_WAIT是基本每一应用服务器都有

**Comment by 2881099** [comment]
统计一下有多少，集群的连接数最少是50*3

每个节点都有一个 pool

**Comment by Yuyg77** [comment]
> 统计一下有多少，集群的连接数最少是50*3
> 
> 每个节点都有一个 pool

每台大概有100个左右

**Comment by Yuyg77** [comment]
> > 统计一下有多少，集群的连接数最少是50*3
> > 每个节点都有一个 pool
> 
> 每台大概有100个左右

redis集群设置有180s的关闭探测服务，和这个会不会有关系

**Comment by Yuyg77** [comment]
现在的集群连接设置的是poolsize=150，preheat=50，idleTimeout=15000

**Comment by Yuyg77** [comment]
> 现在的连接设置的是poolsize=150，preheat=50，idleTimeout=15000

**Comment by 2881099** [comment]
100个左右是正常的啊，你的集群是几个master

**Comment by Yuyg77** [comment]
感觉是不是应该把超时时间（connectTimeout）设为大一些，现在还是默认的5000

**Comment by Yuyg77** [comment]
> 100个左右是正常的啊，你的集群是几个master

3主 3从，至于你说的这个正常，原因能方便解释一下嘛

**Comment by 2881099** [comment]
集群的原理，每个节点都要用socket，预热数50，实际要创建3个连接池，150个连接

**Comment by 2881099** [comment]
如果在意连接数过多，可以设置一个合适的预热数量。一般内网20个预热也够

**Comment by Yuyg77** [comment]
> > 100个左右是正常的啊，你的集群是几个master
> 
> 3主 3从，至于你说的这个正常，原因能方便解释一下嘛

每一台100个，10台服务器就1000个，如果说是正常现象，具体能解释一下嘛，我这边不是很理解

> 集群的原理，每个节点都要用socket，预热数50，实际要创建3个连接池，150个连接

就是说预热的连接，应用这边是不会主动关闭的是吗？即使redis服务器主动关闭了连接

**Comment by 2881099** [comment]
单机版50个。集群本身就有负载的功能，每个节点只有单机的三分之一流量。所以需要的预热数量会更低

**Comment by 2881099** [comment]
是的，不会主动关闭连接。

**Comment by Yuyg77** [comment]
> 是的，不会主动关闭连接。

好的   我再和dba沟通一下，谢谢了！

**Comment by Yuyg77** [comment]
> 是的，不会主动关闭连接。

现在是这样的情况，redis服务有设置超时时间30s，如果客户端这边的一直不关闭，就造成了现在的这种情况，出现close wait，这样，会不会引发什么问题

**Comment by 2881099** [comment]
不会有问题的，服务器30秒断开，csredis 设置 idletimeout=20000 就行了

**Comment by Yuyg77** [comment]
麻烦问一下，连接集群还需要配置poolsize，idleTimeout，connectTimeout以及preheat这几个参数吗？

**Comment by 2881099** [comment]
如果没出问题可以不设

**Comment by lonfme** [comment]
```
root@web01:/data/www# ss -tn
State                 Recv-Q            Send-Q                             Local Address:Port                                  Peer Address:Port                     
CLOSE-WAIT            1                 0                                      10.36.1.3:58956                                192.168.154.6:6690             
CLOSE-WAIT            1                 0                                      10.36.1.3:46190                                192.168.154.1:6690             
CLOSE-WAIT            1                 0                                      10.36.1.3:55526                                192.168.154.5:6690             
CLOSE-WAIT            1                 0                                      10.36.1.3:39302                                192.168.154.5:6690
```

应用程序侧关于 Redis server 有大量 CLOSE-WAIT ，并且系统网络 Recv-Q 接收队列，有一个报文未被处理

**Comment by 2881099** [comment]
@lonfme 已知环境是集群，netstat 是在哪个节点查看的

**Comment by lonfme** [comment]
csredis 3.6.2
.net core 3.1
redis server 4.0.10 cluster
os centos7 docker

是在 dotnet 应用服务器上查看的

**Comment by 2881099** [comment]
应用服务器统计，有多少个连接，因为看你发出来的代码做了预热。连接数是，两个 CSRedisClient 对象 * poolsize * 集群的节点数量

你计算一下看对不对的上

**Comment by lonfme** [comment]
应用服务器总共有 79 个redis 链接，16个状态是 ESTAB，63 个状态是 CLOSE-WAIT。
poolsize是300，预热数是5。
两个 CSRedisClient 对象，一个集群节点是 3主3从，另外一个集群节点是 9 主9从

**Comment by 2881099** [comment]
@lonfme 
3*5 + 9*5 = 60，你给的 79 个应该是预热之后增加的。

**Comment by lonfme** [comment]
是的，这个是线上业务已经跑了两三个小时了。

**Comment by 2881099** [comment]
@lonfme 数量是在掌控范围内的，放心。

**Comment by lonfme** [comment]
现在是偶尔有一堆报错出来。
```
CSRedis.RedisClientException: Connection was not opened
   at CSRedis.CSRedisClient.GetAndExecuteAsync[T](RedisClientPool pool, Func`2 handerAsync, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalarAsync[T](String key, Func`3 handerAsync)
```

```
	System.Exception: 【192.168.154.6:6690/0】状态不可用，等待后台检查程序恢复方可使用。Connect to server timeout
 ---> CSRedis.Internal.IO.RedisSocketException: Connect to server timeout
   at CSRedis.Internal.IO.RedisSocket.Connect(EndPoint endpoint, Int32 timeout)
   at CSRedis.Internal.RedisConnector.Connect(Int32 timeout)
   at CSRedis.RedisClient.Connect(Int32 timeout)
   at CSRedis.RedisClientPool.Return(Object`1 obj, Exception exception, Boolean isRecreate)
   --- End of inner exception stack trace ---
   at CSRedus.Internal.ObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
   at CSRedus.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Get(String key)
   at CSRedis.CSRedisClient.CacheShell[T](String key, Int32 timeoutSeconds, Func`1 getData)
```

偶发性的，而且是个别应用，不是所有应用同时报错，我们应用部署了很多个实例。

**Comment by 2881099** [comment]
这个错误是 connect server timeout，连接超时。192.168.154.6:6690/0 这个节点

**Comment by lonfme** [comment]
CSRedis.RedisClientException: Connection was not opened

那这个错误呢？

**Comment by 2881099** [comment]
这个错误是因为连接不上，随后抛出的

**Comment by lonfme** [comment]
感谢 👍
