### ISSUE TITLE
集群环境下使用StartPipe报错

### ISSUE THREAD

**Issue by liuyl1992** [2881099/csredis#307]
```csharp
var result = RedisHelper.StartPipe()
                .Del("1")
               .Del("2").EndPipe();
```

服务器调用没报错，但是后台日志打印如下
![image](https://user-images.githubusercontent.com/16396828/85112521-50ba5680-b248-11ea-96d6-941b4bd23119.png)
本地使用的同一个redis集群环境，本地没异常，服务器运行会报以上异常

**Comment by 2881099** [comment]
服务器限制，不能跨节点操作

**Comment by liuyl1992** [comment]
> 服务器限制，不能跨节点操作

那这个是可以配置服务器吗，还是集群不能使用StartPipe

**Comment by 2881099** [comment]
你的服务器不支持

**Comment by liuyl1992** [comment]
> 你的服务器不支持

服务器能配置到支持pipeline 操作多节点吗

**Comment by 2881099** [comment]
如果你用阿里云腾讯那些，应该不能

**Comment by 2881099** [comment]
主要问题是，不能跨节点操作

**Comment by liuyl1992** [comment]
> 如果你用阿里云腾讯那些，应该不能

用的是自己搭建的，按道理是可以吗，是有开关配置的吗，让我们运维大佬看看

**Comment by 2881099** [comment]
现在是什么错误？

**Comment by liuyl1992** [comment]
> 现在是什么错误？

就是最上面贴的图上显示的错误

**Comment by 2881099** [comment]
图片显示不出来，文本描述一下

**Comment by liuyl1992** [comment]
```json
 csreids 错误【IP:7001/0】：MOVED 12509 IP:7001    at CSRedis.Internal.RedisPipeline.Flush()
    at CSRedis.Internal.RedisConnector.EndPipe()
   at CSRedis.RedisClient.EndPipe()
    at CSRedis.CSRedisClientPipe`1.EndPipe()


csreids 错误【ip:7000/0】：MOVED 12509ip:7001    at CSRedis.Internal.RedisPipeline.Flush()
2020-06-19T10:18:58.230717558Z    at CSRedis.Internal.RedisConnector.EndPipe()
2020-06-19T10:18:58.230722758Z    at CSRedis.RedisClient.EndPipe()
2020-06-19T10:18:58.230727858Z    at CSRedis.CSRedisClientPipe`1.EndPipe()
```

**Comment by 2881099** [comment]
连接串的 testcluster=true 启动了吗

**Comment by 2881099** [comment]
这个错误的原因是 a b 划分在不同的节点导致的

**Comment by 2881099** [comment]
极端情况会报错，正在使用的时候，如果 slot 重新分配的情况下会报错。

**Comment by liuyl1992** [comment]
> testcluster

没有设置这个配置

**Comment by liuyl1992** [comment]
> 这个错误的原因是 key 1 key 2 划分在不同的节点导致的

是的，我要删除不同节点的key，set的时候分配节点是redis计算key后得出的，可能落在不同节点，这个没问题，那我配置 testcluster=true就可以了吗

**Comment by liuyl1992** [comment]
加了 testcluster=true 正常了

**Comment by liuyl1992** [comment]
如果非集群模式加 testcluster=true 没影响吧

**Comment by 2881099** [comment]
> 如果非集群模式加 testcluster=true 没影响吧

没影响
