### ISSUE TITLE
在BackgroundService里调用BRPop会阻塞主线程，这是为啥？

### ISSUE THREAD

**Issue by 1100100** [2881099/csredis#311]
在BackgroundService里调用BRPop会阻塞主线程，这是为啥？

**Comment by 1100100** [comment]
![image](https://user-images.githubusercontent.com/17895675/86465390-167ea800-bd64-11ea-93dd-1cfba5234faf.png)

**Comment by 2881099** [comment]
这个操作是阻塞操作，如果不想阻塞可以套一层线程再执行

**Comment by 1100100** [comment]
还没来得及看源码，咱内部阻塞是用的什么方式阻塞呢

**Comment by 2881099** [comment]
brpop 命令是等待服务器返回，所以阻塞在socket 上面

**Comment by 1100100** [comment]
这个地方我还没搞清楚乍回事，我在service的循环里调用其他代码没啥问题，都是一个无限循环，但是调用这个方法就会阻塞主线程，导致服务启动不起来，还得研究下，新开一个线程是没有问题的

**Comment by 1100100** [comment]
当redis里没有值时，brpop在等待时抛出了异常

csreids 错误【127.0.0.1:6379/3】：Unable to read data from the transport connection: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.    at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.NodesNotSupport[T](String[] keys, T defaultValue, Func`3 callback)
   at CSRedis.CSRedisClient.BRPop(Int32 timeout, String[] keys)
   at RedisHelper`1.BRPop(Int32 timeout, String[] keys)
   at WebApi.HostedService.SignUpWriteDataBaseService.ExecuteAsync(CancellationToken stoppingToken) in E:\WorkSpace\Jobs\2020-05-28环保汽车\WebApi\HostedService\SignUpWriteDataBaseService.cs:line 46
fail: WebApi.HostedService.SignUpWriteDataBaseService[0]
      出现错误：Unable to read data from the transport connection: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.

**Comment by 2881099** [comment]
timeout 参数值要小于 socket readtimeout 即连接串的 synctimeout 值，默认是什么10秒
