### ISSUE TITLE
EndPipe()会自动释放连接吗

### ISSUE THREAD

**Issue by scenerytickets** [2881099/csredis#315]
当前我们这边系统有大量的redis连接，环境使用的是阿里云的Redis，想咨询下EndPipe在程序每次调用之后，会默认释放连接吗？

**Comment by 2881099** [comment]
物理连接不会释放，会返回连接池。

**Comment by scenerytickets** [comment]
@2881099 ，请教一下，物理连接是什么意思？

**Comment by 2881099** [comment]
> @2881099 ，请教一下，物理连接是什么意思？

socket 链接

**Comment by scenerytickets** [comment]
@2881099 ，自己手动释放的话，只能通过using()嘛？

**Comment by scenerytickets** [comment]
还有一个问题，连接字符串中的idleTimeout，这个值的意思是，设置的这个时间段以内，会话会一直保持，直到到设置的值，才会自动释放连接的嘛？

**Comment by 2881099** [comment]
idletimeout 是一种防治服务端主动断开socket的一种方法。客户端本身不会主动断开socket。

**Comment by scenerytickets** [comment]
> idletimeout 是一种防治服务端主动断开socket的一种方法。客户端本身不会主动断开socket。

那是不是我客户端的功能，其实是没有办法主动释放连接的。我客户端只能自己主动断开跟服务端的连接，而Redis会话连接只能是服务端在idletimeout设置值阈值外，自动释放的？

**Comment by 2881099** [comment]
是的

**Comment by scenerytickets** [comment]
我们这边现在碰到高并发请求的时候，我们这边的get和set会特别多，造成Redis会话短时间内大幅度的增加，然后就报错：
异常信息：SafeObjectPool.Get 获取超时（10秒）。
错误源：CSRedisCore
运行类型：System.TimeoutException
异常函数：CSRedus.Internal.ObjectPool.Object`1[T] Get(System.Nullable`1[System.TimeSpan])
堆栈信息：   at CSRedus.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteArray[T](String[] key, Func`3 hander)
   at CSRedis.CSRedisClient.MGet(String[] keys)
   at RedisHelper`1.MGet(String[] keys)
是因为预起的连接数不够的嘛？增大pool size？

**Comment by 2881099** [comment]
是的，你看每秒多少次访问

**Comment by 2881099** [comment]
如果访问的是远程redis，是会处理不过来，优化一下网络环境。

**Comment by scenerytickets** [comment]
> 如果访问的是远程redis，是会处理不过来，优化一下网络环境。

我们使用的都是阿里云环境，ECS中的容器去访问阿里云的Redis。

**Comment by 2881099** [comment]
加大poolsize=500, preheat=200

参数说明看 readme，另外咨询阿里云如果优化网络访问。
