### ISSUE TITLE
Connect to server timeout

### ISSUE THREAD

**Issue by bbenph** [2881099/csredis#324]
最初redis自己搭建的, 后来出问题买的亚马逊云的redis服务 ,还是一样的错误
平时没问题的, 凌晨流量大时候必会报错

异常: System.Exception: 【xxxxxxxxxxxxxxxxx:6379/15】状态不可用，等待后台检查程序恢复方可使用。Connect to server timeout ---> CSRedis.Internal.IO.RedisSocketException: Connect to server timeout
   at CSRedis.Internal.IO.RedisSocket.Connect(EndPoint endpoint, Int32 timeout)
   at CSRedis.Internal.RedisConnector.Connect(Int32 timeout)
   at CSRedis.RedisClient.Connect(Int32 timeout)
   at CSRedis.RedisClientPool.Return(Object`1 obj, Exception exception, Boolean isRecreate)
   --- End of inner exception stack trace ---
   at CSRedis.Internal.ObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
   at CSRedis.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Get[T](String key)
   at RedisHelper`1.Get[T](String key)
   at Models.Helper.CacheLiveFilter.OnActionExecuting(ActionExecutingContext actionContext) in D:\react\CacheLiveFilter.cs:line 25
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Lottery.Tasks.RequestResponseLoggingMiddleware.Invoke(HttpContext context) in D:\react\RequestResponseLoggingMiddleware.cs:line 47

**Comment by 2881099** [comment]
连接超时，看参数设置，默认是5面。

另外要注意 dns 解析的速度，有可能慢在这里导致了超时

**Comment by bbenph** [comment]
> 连接超时，看参数设置，默认是5面。
> 
> 另外要注意 dns 解析的速度，有可能慢在这里导致了超时

cache.amazonaws.com:6379,defaultDatabase=15,syncTimeout=5000,preheat=3,testcluster=false,idleTimeout=15000,tryit=2,poolsize=1000

**Comment by 2881099** [comment]
connectTimeout=30000

**Comment by bbenph** [comment]
> connectTimeout=30000

好的 谢谢 我试一下

**Comment by 2881099** [comment]
测试一下 cache.amazonaws.com 并发解析速度

**Comment by DarinHan** [comment]
idleTimeout能设置断点么？我也碰到这个问题，我把idleTimeout设置成3000,300个线程跑下来没啥问题，但是我不知道idleTimeout设置成3000会不会有其他影响

**Comment by 2881099** [comment]
3000太少了，这个是3秒不用的，下一次就重新连接 socket，主要是防止服务器主动断开连接的情况，一般30秒比较好。

**Comment by 2881099** [comment]
connect time out 是连接超时，默认是5秒连不上就报这个错误。网络情况好的环境不会出这个问题。连接超时参数也可以设置。
