### ISSUE TITLE
System.IO.EndOfStreamException: Unexpected end of stream; expected type 'MultiBulk'

### ISSUE THREAD

**Issue by kinsen** [2881099/csredis#35]
调用*RedisHelper.Keys*频繁抛出异常.
```
System.IO.EndOfStreamException: Unexpected end of stream; expected type 'MultiBulk'
   at CSRedis.Internal.IO.RedisReader.ExpectType(RedisMessage expectedType)
   at CSRedis.Internal.Commands.RedisArray.Generic`1.Parse(RedisReader reader)
   at CSRedis.Internal.RedisConnector.Call[T](RedisCommand`1 command)
   at CSRedis.RedisClient.Write[T](RedisCommand`1 command)
   at CSRedis.RedisClient.Keys(String pattern)
   at CSRedis.CSRedisClient.Keys(String pattern)
   at RedisHelper.Keys(String pattern)
   at NbCRM.Account.TokenHelper.GetXTokenFromRedis(String plainToken) in C:\Projects\NbCRM\NbCRM.Account\src\NbCRM.Account\Helper\TokenHelper.cs:line 75
   at NbCRM.Account.Impl.UserServiceImpl.GetUserPath(Querys request, ServerCallContext context) in C:\Projects\NbCRM\NbCRM.Account\src\NbCRM.Account\Impl\UserServiceImpl.cs:line 750
   at Grpc.Core.Internal.UnaryServerCallHandler`2.<>c__DisplayClass4_2.<<HandleCall>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by 2881099** [comment]
怎么重现问题。我测试没发现问题

**Comment by kinsen** [comment]
这个问题很奇怪,Windows上没有出现,Linux频繁出现,目前还没发现100%复现的方式..

**Comment by 2881099** [comment]
keys 查的参数是什么？
预计返回数据多少条，中间有没有特别长的keyname？
同样的参数，在redis-cli执行，是否正常？

截图多收集相关数据

**Comment by 2881099** [comment]
public void ExpectType(RedisMessage expectedType)
        {
            RedisMessage type = ReadType();
            if ((int)type == -1)
                throw new EndOfStreamException("Unexpected end of stream; expected type '" + expectedType + "'");
            if (type != expectedType)
                throw new RedisProtocolException(String.Format("Unexpected response type: {0} (expecting {1})", type, expectedType));
        }


服务端返回-1，才会出这个错误

**Comment by kinsen** [comment]
不是服务端返回-1,应该是流结束了..
查询的参数 一般为 AX*这样的. 长度不超过64.
cli中查询很正常.

**Comment by 2881099** [comment]
我这里没办法重现问题啊，下面的代码测试没报错。

```csharp
for (var a = 0; a < 50; a++) {
	new Thread(() => {
		for (int i = 0; i < 100; i++) {
			Task.Run(async () => {
				try {
					var keysall = RedisHelper.Keys("*");
					var keys = RedisHelper.Keys("lkjsdglkjskldgk*slkdgjlksdjgkl");

					Console.WriteLine(keys.Length + "/" + keysall.Length);
				} catch (Exception ex) {
					Console.WriteLine(ex);
				}

				await Task.Delay(200);
			}).Wait();
		}
	}).Start();
}
```

**Comment by 2881099** [comment]
你那里可以必报错误吗？

**Comment by zhyuxwz** [comment]
会不会是因为redis的timeout配置的原因？我这边在将timeout配置为非0的值的时候也会遇到这样的问题

**Comment by DrDao** [comment]
经常遇到这个问题....不管是windows和linux下

**Comment by DrDao** [comment]
Unable to read data from the transport connection: 你的主机中的软件中止了一个已建立的连接。. ---> System.Net.Sockets.SocketException: 你的主机中的软件中止了一个已建立的连接。

Unexpected end of stream; expected type 'Bulk'

**Comment by 2881099** [comment]
连接终止了，然后跟着读取数据不正确。

可下载源码搜索【Unexpected end of stream; expected type】，只有一个地方

**Comment by JimReal** [comment]
我也遇到同样的问题，目前可以确定的是我这边使用HGetAllAsync方法是必现的，改为HGetAll不出现此问题，或许从异步方面排查会有线索

**Comment by yescent** [comment]
使用 HGetAll方法时候出现，csreids 错误【10.0.0.36:6379/0】：Unexpected end of stream; expected type 'MultiBulk'; data =     at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)

**Comment by 2881099** [comment]
@JimReal @yescent  是必然出现的吗？增加 tryit=1 参数试试

**Comment by yescent** [comment]
> @JimReal @yescent 是必然出现的吗？增加 tryit=1 参数试试

增加  tryit=1 还是报错
系统为linux，timeout设置为0

**Comment by 2881099** [comment]
是否开启了 ssl

**Comment by yescent** [comment]
没有开启

**Comment by 2881099** [comment]
使用同步方法呢？

**Comment by 2881099** [comment]
是 HGetAllAsync 还是 HGetAll 出的错？

**Comment by yescent** [comment]
HGetAll

**Comment by 2881099** [comment]
代码发出来看下

**Comment by yescent** [comment]
`    public class RedisDb: IRedisDb
    {
        public  List<T> HashGetAll<T>(string key)
        {
            List<T> list = new List<T>();
            try
            {
                return RedisHelper.HGetAll<T>(key)?.Select(x => x.Value).ToList();
            }
            catch (Exception) { }
            return list;
        }
    }`


`
            var csredis = new CSRedisClient(null,connectionString);
            //初始化 RedisHelper
            RedisHelper.Initialization(csredis);
`

**Comment by JimReal** [comment]
`var res = RedisHelper.HGetAll(string.Format(gxin_users_{0}, id));`
id是一个guid。

**Comment by vincentelite** [comment]
is there a solution ?we run into the same Dilemma.

**Comment by JimReal** [comment]
There is nothing for the time being，you can try async or not async in two ways.

**Comment by 2881099** [comment]
Did redis-server turn SSL on?
