### ISSUE TITLE
Unexpected response type: MultiBulk (expecting Bulk)

### ISSUE THREAD

**Issue by lei13720831568** [2881099/csredis#355]
版本 v3.6.5
使用BRPopLPush时日志出现如下,BRPopLPush 的timeout为 5,  连接串:127.0.0.1,password=,defaultDatabase=1,prefix=biz:,poolsize=20,preheat=10

| csreids 错误【redis:6379/5】：Unexpected response type: MultiBulk (expecting Bulk)    at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
 |    at CSRedis.CSRedisClient.NodesNotSupport[T](String[] keys, T defaultValue, Func`3 callback)
 |    at CSRedis.CSRedisClient.BRPopLPush[T](String source, String destination, Int32 timeout)
|    at RedisHelper`1.BRPopLPush[T](String source, String destination, Int32 timeout)

**Comment by 2881099** [comment]
连接串增加 tryit=3 试试

重新开发了全新的组件 FreeRedis

欢迎关注 https://github.com/2881099/FreeRedis
