### ISSUE TITLE
Unexpected end of stream; expected type 'Int'; data = ''

### ISSUE THREAD

**Issue by yjqGitHub** [2881099/csredis#359]
您好，近期使用csredis的时候发现一个问题 Unexpected end of stream; expected type 'Int'; data = ''

测试代码如下：
# 执行方法
        public static void RunTest()
        {
            Parallel.For(0, 2000, async i =>
            {
                int jj = i;
                int j = 0;
                while (j < 150)
                {
                    try
                    {   
                       await RedisHelper.IncrByAsync("TestredisCount", 1);
                   }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"{jj},{j},shibai");
                        Console.WriteLine(ex);
                   }
                    j++;
                }
            });
        }

# 循环执行
              for (int i = 0; i < 10; i++)
                {
                    Console.WriteLine("开始执行->" + i.ToString());
                    RunTest();
                    Console.WriteLine("执行完成->" + i.ToString());
                    System.Threading.Thread.Sleep(3000);
                }
# 控制台输出
开始执行->0
执行完成->0
开始执行->1
`System.IO.EndOfStreamException: Unexpected end of stream; expected type 'Int'; data = ''
   at CSRedis.CSRedisClient.GetAndExecuteAsync[T](RedisClientPool pool, Func`2 handerAsync, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalarAsync[T](String key, Func`3 handerAsync)
   at DataAccessExample.PoolTest.<>c.<<RunTest>b__16_0>d.MoveNext() in D:\WorkFiles\Code\public\warship\Warship\DataAccessExample\PoolTest.cs:line 82`

链接字符串为：
,poolsize=300,connectTimeout=10000,idleTimeout=170000,tryit=3,testcluster=false

当i=1时，即第二轮执行时，他必现这个异常，但是把IncrByAsync改为IncrBy同步方法去执行时，他不会报任何错误，希望我的例子对您有用

**Comment by 2881099** [comment]
redis单机版，测试了没有

**Comment by yjqGitHub** [comment]
> redis单机版，测试了没有

这个没有 我们生产环境就是集群的，所以就没有去测试单机版的

**Comment by 2881099** [comment]
testcluster=false，是腾讯云，阿里云环境吗？

他们加了一层网络代理，有可能会影响 resp 协议返回结果。

**Comment by yjqGitHub** [comment]
> testcluster=false，是腾讯云，阿里云环境吗？
> 
> 他们加了一层网络代理，有可能会影响 resp 协议返回结果。

这个去掉也是一样的 我们是阿里云的，但是把异步改为同步他就是一点都不会报错的。用异步方法就是必现的

**Comment by 2881099** [comment]
CSRedisCore 用的哪个版本

**Comment by yjqGitHub** [comment]
> CSRedisCore 用的哪个版本

3.6.5

**Comment by 2881099** [comment]
本地集群环境测试正常，图片如下：

![image](https://user-images.githubusercontent.com/16286519/104123998-30d7b500-5389-11eb-8dba-1181be07fcb1.png)

**Comment by 2881099** [comment]
开始执行->0
执行完成->0
开始执行->1
执行完成->1
开始执行->2
执行完成->2
开始执行->3
执行完成->3
开始执行->4
执行完成->4
开始执行->5
执行完成->5
开始执行->6
执行完成->6
开始执行->7
执行完成->7
开始执行->8
执行完成->8

**Comment by yjqGitHub** [comment]
谢谢！
这我也不知道为什么了，我这边的集群是三主三从，您那边能大概定位我这边发生这样的问题是因为什么导致的吗？网络还是集群部署的方案？

**Comment by YahuiWong** [comment]
遇到了一个的问题 mark一下
