### ISSUE TITLE
仍然不可用，下一次恢复检查时间：02/02/2021 02:01:33，错误：(Connect to server timeout)

### ISSUE THREAD

**Issue by youweimao** [2881099/csredis#368]
我之前做了HOST=>IP, 本以为已经修复好了，但今天在集群测试的时候，还是会遇到这种问题。
1000个并发没有发现问题，2000个并发就出问题了。
集群环境：3台WEB,1台Redis
老版本
错误：
仍然不可用，下一次恢复检查时间：02/02/2021 02:01:33，错误：(Connect to server timeout)

一直这样，而且无法恢复。

**Comment by 2881099** [comment]
有可能被服务器认为攻击，拒绝连接？

**Comment by lihanping2016** [comment]
我用jmeter做高并发压测的时候也报了这个错，连接串中加了tryit=3解决了该问题

**Comment by lihanping2016** [comment]
高并发情况下，建议加上tryit=3配置

**Comment by lihanping2016** [comment]
> 我之前做了HOST=>IP, 本以为已经修复好了，但今天在集群测试的时候，还是会遇到这种问题。
> 1000个并发没有发现问题，2000个并发就出问题了。
> 集群环境：3台WEB,1台Redis
> 老版本
> 错误：
> 仍然不可用，下一次恢复检查时间：02/02/2021 02:01:33，错误：(Connect to server timeout)
> 
> 一直这样，而且无法恢复。

高并发情况下，建议加上tryit=3配置

**Comment by tongfei-github** [comment]
解决了吗？楼主，我这边也出现这个问题。@youweimao

**Comment by Seamless2014** [comment]
解决了嘛？楼主，我这边并发大的话，也出现这样的问题
System.Exception: 【services.zkgt.com:6379/0】Status unavailable, waiting for recovery. Connect to server timeout
 ---> CSRedis.Internal.IO.RedisSocketException: Connect to server timeout
   at CSRedis.Internal.IO.RedisSocket.Connect(EndPoint endpoint, Int32 timeout)
   at CSRedis.Internal.RedisConnector.Connect(Int32 timeout)
   at CSRedis.RedisClient.Connect(Int32 timeout)
   at CSRedis.RedisClientPool.Return(Object`1 obj, Exception exception, Boolean isRecreate)
   --- End of inner exception stack trace ---
   at CSRedis.Internal.ObjectPool.ObjectPool`1.GetFree(Boolean checkAvailable)
   at CSRedis.Internal.ObjectPool.ObjectPool`1.GetAsync()
   at CSRedis.CSRedisClient.GetClientAsync(RedisClientPool pool)
   at CSRedis.CSRedisClient.GetAndExecuteAsync[T](RedisClientPool pool, Func`2 handerAsync, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalarAsync[T](String key, Func`3 handerAsync)
