### ISSUE TITLE
关于重连后订阅恢复的问题

### ISSUE THREAD

**Issue by parkycai** [2881099/csredis#37]
目前测了一下用CSRedisClient订阅之后，模拟断一下网然后恢复（禁用网卡），重新连上之后，就无法收到原先订阅的Channel了。
而且发现网络断一下之后，所有的API调用都会巨卡，感觉是每个命令都达到了超时时间。版本是2.6.9。测试代码如下：

`
        private static async Task TestRedis()
        {
            try
            {
                var client = new CSRedisClient("192.168.10.40:6379,password=foo:bared,defaultDatabase=1");
                RedisHelper.Initialization(client,null,null);
                RedisHelper.Subscribe(("Test", arg => Console.WriteLine(arg.Body)));
                for (int i = 0; i < 100; i++)
                {
                    try
                    {
                        Console.WriteLine($"pub {i}--");
                        await client.PublishAsync("Test", $"Test{i}**");
                        Console.WriteLine($"---------");
                        await Task.Delay(200);
                    }
                    catch (Exception)
                    {
                    }
                }
                
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
`

**Comment by parkycai** [comment]
测试代码如下，中间断一下网络。

```                var client = new CSRedisClient("192.168.1.1:6379,password=foo:bared,defaultDatabase=1");
                RedisHelper.Initialization(client,null,null);
                RedisHelper.Subscribe(("Test", arg => Console.WriteLine(arg.Body)));
                for (int i = 0; i < 100; i++)
                {
                    try
                    {
                        Console.WriteLine($"pub {i}--");
                        await client.PublishAsync("Test", $"Test{i}**");
                        Console.WriteLine($"---------");
                        await Task.Delay(200);
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex);
                    }
                }

**Comment by 2881099** [comment]
好的，我之前内测出这个情况

redis-server 是127.0.0.1吧？

**Comment by parkycai** [comment]
是另一台机上的，不然没法模拟断网了

**Comment by 2881099** [comment]
pub 0--
---------
Test0**
pub 1--
Test1**
---------
pub 2--
---------
Test2**
pub 3--
Test3**
---------
pub 4--
---------
Test4**
pub 5--
Test5**
---------
pub 6--
---------
Test6**
pub 7--
Test7**
---------
pub 8--
Test8**
---------
pub 9--
Test9**
---------
pub 10--
---------
Test10**
pub 11--
Test11**
---------
pub 12--
---------
Test12**
pub 13--
Test13**
---------
pub 14--
---------
Test14**
pub 15--
---------
pub 16--
Test15**
Test16**
---------
pub 17--
Test17**
---------
pub 18--
---------
Test18**
pub 19--
Test19**
---------
pub 20--
---------
Test20**
pub 21--
Test21**
---------
pub 22--
---------
Test22**
pub 23--
Test23**
---------
pub 24--
---------
Test24**
pub 25--
Test25**
---------
pub 26--
---------
Test26**
pub 27--
Test27**
---------
pub 28--
---------
Test28**
pub 29--
Test29**
---------
pub 30--
Test30**
---------
pub 31--
Test31**
---------
pub 32--
Test32**
---------
pub 33--
Test33**
---------
pub 34--
Test34**
---------
pub 35--
Test35**
---------
pub 36--
---------
Test36**
pub 37--
Test37**
---------
pub 38--
---------
Test38**
pub 39--
Test39**
---------
pub 40--
---------
Test40**
pub 41--
Test41**
---------
pub 42--
Test42**
---------
pub 43--
Test43**
---------
pub 44--
---------
Test44**
pub 45--
Test45**
---------
pub 46--
---------
Test46**
pub 47--
Test47**
---------
pub 48--
---------
Test48**
pub 49--
Test49**
---------
pub 50--
Test50**
---------
pub 51--
Test51**
---------
pub 52--
---------
Test52**
pub 53--
Test53**
---------
pub 54--
---------
Test54**
pub 55--
Test55**
---------
pub 56--
Test56**
---------
pub 57--                                     <------断开 wifi

csreids 错误【47.74.4.44:6333/13】：Unable to read data from the transport connection: 由于连接方在一段时间后没有正确答 复或连接的主机没有反应，连接尝试失败。.
redis-server 断开重启后，因连接池内所有连接状态无法更新，导致每个连接在重启后的第一次操作仍会失败。
csredis 内部统一处理错误，一量发现错误，连接池内所有连接下次操作将触发 Ping() 条件，解决上述问题。
缺陷：如果错误为非 socket 错误，将导致性能下降。根据异常信息优化程序使用方法，可以解决这个缺陷。

System.IO.IOException: Unable to read data from the transport connection: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。. ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反 应，连接尝试失败。
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at CSRedis.CSRedisClient.GetConnectionAndExecuteAsync[T](ConnectionPool pool, Func`2 handle) in C:\Users\28810\Desktop\github\csredis\CSRedis\CSRedisClientAsync.cs:line 17
   at CSRedis.CSRedisClient.PublishAsync(String channel, String data) in C:\Users\28810\Desktop\github\csredis\CSRedis\CSRedisClientAsync.cs:line 328
   at es.WebHost.Startup.<>c__DisplayClass0_0.<<-ctor>b__4>d.MoveNext() in C:\Users\28810\Desktop\genms_shop\src\WebHost\Startup.cs:line 89
pub 58--                           <----连接wifi
Test58**
---------
pub 59--
Test59**
---------
pub 60--
Test60**
---------
pub 61--
Test61**
---------
pub 62--
---------
Test62**
pub 63--
Test63**
---------
pub 64--
Test64**
---------
pub 65--
Test65**
---------
pub 66--
---------
Test66**
pub 67--
Test67**
---------
pub 68--
Test68**
---------
pub 69--
Test69**
---------
pub 70--
Test70**
---------
pub 71--
Test71**
---------
pub 72--
---------
Test72**
pub 73--
Test73**
---------
pub 74--
Test74**
---------
pub 75--
Test75**
---------
pub 76--
---------
Test76**
pub 77--
---------
Test77**
pub 78--
---------
Test78**
pub 79--
Test79**
---------
pub 80--
Test80**
---------
pub 81--
Test81**
---------
pub 82--
---------
Test82**
pub 83--
Test83**
---------
pub 84--
Test84**
---------
pub 85--
Test85**
---------
pub 86--
---------
Test86**
pub 87--
Test87**
---------
pub 88--
---------
Test88**
pub 89--
Test89**
---------
pub 90--
---------
Test90**
pub 91--
Test91**
---------
pub 92--
---------
Test92**
pub 93--
Test93**
---------
pub 94--
---------
Test94**
pub 95--
Test95**
---------
pub 96--
---------
Test96**
pub 97--
Test97**
---------
pub 98--
---------
Test98**
pub 99--
Test99**
---------                            <-------结束

## 测试条件：

连接远程redis-server服务器，poolsize=5

## 测试完成后 redispool 的状态

{"47.74.4.44:6333/13":{"freeConnections":4,"allConnections":5,"getConnectionQueue":0,"getConnectionAsyncQueue":0}

**Comment by 2881099** [comment]
经测试发现，订阅逻辑有问题。表现为连接池过小，并且请求量巨大的时候，如果断开连接重新订阅时，发现订阅方法的 GetConnection 根本无法获取到资源。

晚上把订阅逻辑重新做了一遍，经过多次压力测试已经正常了。
新的逻辑为，连接永久占用，除非取消订阅才归回连接池。

测试方法：断网，服务器重启，均能短时间内重新订阅收消息。

代码使用方法不遍，Subscribe/PSubscribe 函数返回值变了，返回的对象可以手工取消订阅。

```
var subscr = RedisHelper.Subscribe(("Test", arg => Console.WriteLine(arg.Body)));
subscr.UnSubscribe(); //或者
subscr.Dispose(); //都可以取消订阅，并归还资源给pool
```

**Comment by parkycai** [comment]
还是有发现卡死，输出如下：
```
正在订阅【192.168.10.40:6379/1】(channels:Test)/(chans:Test)[09:56:04]pub 0--

tart first.
2[09:56:04]---------
[09:56:04]Test0**
[09:56:04]pub 1--
[09:56:04]---------
[09:56:04]Test1**
[09:56:05]pub 2--
[09:56:05]---------
[09:56:05]Test2**
[09:56:05]pub 3--
[09:56:05]Test3**
[09:56:05]---------
[09:56:05]pub 4--
[09:56:05]Test4**
[09:56:05]---------
[09:56:05]pub 5--
[09:56:05]---------
[09:56:05]Test5**
[09:56:06]pub 6--
[09:56:06]---------
[09:56:06]Test6**
[09:56:06]pub 7--
[09:56:06]---------
[09:56:06]Test7**
[09:56:06]pub 8--
[09:56:06]---------
[09:56:06]Test8**
[09:56:07]pub 9--
[09:56:07]---------
[09:56:07]Test9**
[09:56:07]pub 10--
[09:56:07]---------
[09:56:07]Test10**
[09:56:07]pub 11--
[09:56:07]---------
[09:56:07]Test11**
[09:56:07]pub 12--
[09:56:08]---------
[09:56:08]Test12**
[09:56:08]pub 13--
[09:56:08]---------
[09:56:08]Test13**
[09:56:08]pub 14--
[09:56:09]---------
[09:56:09]Test14**
[09:56:09]pub 15--
[09:56:09]---------
[09:56:09]Test15**
[09:56:09]pub 16--             <-----------这里wifi断开

csreids 错误【192.168.10.40:6379/1】：The operation is not allowed on non-connected sockets.
redis-server 断开重启后，因连接池内所有连接状态无法更新，导致每个连接在重启后的第一次操作仍会失败。
csredis 内部统一处理错误，一量发现错误，连接池内所有连接下次操作将触发 Ping() 条件，解决上述问题。
缺陷：如果错误为非 socket 错误，将导致性能下降。根据异常信息优化程序使用方法，可以解决这个缺陷。

[09:57:27]System.IO.IOException: The operation is not allowed on non-connected sockets.
   at CSRedis.CSRedisClient.GetConnectionAndExecuteAsync[T](ConnectionPool pool, Func`2 handle)
   at CSRedis.CSRedisClient.PublishAsync(String channel, String data)
   at WebApplication1.Program.TestRedis_csredis() in /Users/Wayne/Documents/Workspaces/NetCore/WebApplication1/WebApplication1/Program.cs:line 74
[09:57:27]pub 17--
[09:57:28]System.IO.IOException: The operation is not allowed on non-connected sockets.
   at CSRedis.CSRedisClient.GetConnectionAndExecuteAsync[T](ConnectionPool pool, Func`2 handle)
   at CSRedis.CSRedisClient.PublishAsync(String channel, String data)
   at WebApplication1.Program.TestRedis_csredis() in /Users/Wayne/Documents/Workspaces/NetCore/WebApplication1/WebApplication1/Program.cs:line 74
[09:57:28]pub 18--
[09:57:29]System.IO.IOException: The operation is not allowed on non-connected sockets.
   at CSRedis.CSRedisClient.GetConnectionAndExecuteAsync[T](ConnectionPool pool, Func`2 handle)
   at CSRedis.CSRedisClient.PublishAsync(String channel, String data)
   at WebApplication1.Program.TestRedis_csredis() in /Users/Wayne/Documents/Workspaces/NetCore/WebApplication1/WebApplication1/Program.cs:line 74
[09:57:29]pub 19--
[09:57:30]System.IO.IOException: The operation is not allowed on non-connected sockets.
   at CSRedis.CSRedisClient.GetConnectionAndExecuteAsync[T](ConnectionPool pool, Func`2 handle)
   at CSRedis.CSRedisClient.PublishAsync(String channel, String data)
   at WebApplication1.Program.TestRedis_csredis() in /Users/Wayne/Documents/Workspaces/NetCore/WebApplication1/WebApplication1/Program.cs:line 74
[09:57:30]pub 20--
[09:57:31]System.IO.IOException: The operation is not allowed on non-connected sockets.
   at CSRedis.CSRedisClient.GetConnectionAndExecuteAsync[T](ConnectionPool pool, Func`2 handle)
   at CSRedis.CSRedisClient.PublishAsync(String channel, String data)
   at WebApplication1.Program.TestRedis_csredis() in /Users/Wayne/Documents/Workspaces/NetCore/WebApplication1/WebApplication1/Program.cs:line 74
[09:57:31]pub 21--

csreids 错误【192.168.10.40:6379/1】：The operation is not allowed on non-connected sockets.
redis-server 断开重启后，因连接池内所有连接状态无法更新，导致每个连接在重启后的第一次操作仍会失败。
csredis 内部统一处理错误，一量发现错误，连接池内所有连接下次操作将触发 Ping() 条件，解决上述问题。
缺陷：如果错误为非 socket 错误，将导致性能下降。根据异常信息优化程序使用方法，可以解决这个缺陷。

[09:57:33]System.IO.IOException: The operation is not allowed on non-connected sockets.
   at CSRedis.CSRedisClient.GetConnectionAndExecuteAsync[T](ConnectionPool pool, Func`2 handle)
   at CSRedis.CSRedisClient.PublishAsync(String channel, String data)
   at WebApplication1.Program.TestRedis_csredis() in /Users/Wayne/Documents/Workspaces/NetCore/WebApplication1/WebApplication1/Program.cs:line 74
[09:57:33]pub 22--
[09:57:34]System.IO.IOException: The operation is not allowed on non-connected sockets.
   at CSRedis.CSRedisClient.GetConnectionAndExecuteAsync[T](ConnectionPool pool, Func`2 handle)
   at CSRedis.CSRedisClient.PublishAsync(String channel, String data)
   at WebApplication1.Program.TestRedis_csredis() in /Users/Wayne/Documents/Workspaces/NetCore/WebApplication1/WebApplication1/Program.cs:line 74
[09:57:34]pub 23--
[09:57:35]System.IO.IOException: The operation is not allowed on non-connected sockets.
   at CSRedis.CSRedisClient.GetConnectionAndExecuteAsync[T](ConnectionPool pool, Func`2 handle)
   at CSRedis.CSRedisClient.PublishAsync(String channel, String data)
   at WebApplication1.Program.TestRedis_csredis() in /Users/Wayne/Documents/Workspaces/NetCore/WebApplication1/WebApplication1/Program.cs:line 74
[09:57:35]pub 24--
[09:57:36]System.IO.IOException: The operation is not allowed on non-connected sockets.
   at CSRedis.CSRedisClient.GetConnectionAndExecuteAsync[T](ConnectionPool pool, Func`2 handle)
   at CSRedis.CSRedisClient.PublishAsync(String channel, String data)
   at WebApplication1.Program.TestRedis_csredis() in /Users/Wayne/Documents/Workspaces/NetCore/WebApplication1/WebApplication1/Program.cs:line 74
[09:57:36]pub 25--
[09:57:37]System.IO.IOException: The operation is not allowed on non-connected sockets.
   at CSRedis.CSRedisClient.GetConnectionAndExecuteAsync[T](ConnectionPool pool, Func`2 handle)
   at CSRedis.CSRedisClient.PublishAsync(String channel, String data)
   at WebApplication1.Program.TestRedis_csredis() in /Users/Wayne/Documents/Workspaces/NetCore/WebApplication1/WebApplication1/Program.cs:line 74
[09:57:37]pub 26--            <------------这里恢复
[09:57:37]---------
[09:57:37]Test26**
[09:57:37]pub 27--
[09:57:37]---------
[09:57:37]Test27**
[09:57:38]pub 28--
[09:57:38]---------
[09:57:38]Test28**
[09:57:38]pub 29--
[09:57:38]---------
[09:57:38]Test29**
[09:57:38]pub 30--
[09:57:38]---------
[09:57:38]Test30**
[09:57:38]pub 31--
[09:57:38]---------
[09:57:38]Test31**
[09:57:39]pub 32--
[09:57:39]---------
[09:57:39]Test32**
[09:57:39]pub 33--
[09:57:39]---------
[09:57:39]Test33**
[09:57:39]pub 34--
[09:57:39]---------
[09:57:39]Test34**
[09:57:39]pub 35--
[09:57:39]---------
[09:57:39]Test35**
[09:57:40]pub 36--
[09:57:40]---------
[09:57:40]Test36**
[09:57:40]pub 37--
[09:57:40]---------
[09:57:40]Test37**                  <------------这里暂停了一下执行看了一会儿输出，然后继续执行
[09:58:17]pub 38--
[09:58:17]---------
[09:58:17]Test38**
[09:58:17]pub 39--
[09:58:17]---------
[09:58:17]Test39**
[09:58:18]pub 40--
[09:58:18]---------
[09:58:18]Test40**
[09:58:18]pub 41--
[09:58:18]---------
[09:58:18]Test41**
[09:58:18]pub 42--
[09:58:18]---------
[09:58:18]Test42**
[09:58:18]pub 43--
[09:58:18]---------
[09:58:18]Test43**
[09:58:19]pub 44--
[09:58:19]---------
[09:58:19]Test44**
[09:58:19]pub 45--         <------------这里卡死

```
卡死时候的堆栈如下：
![image](https://user-images.githubusercontent.com/22512293/46252171-ca6c4880-c497-11e8-8c78-134128250759.png)

**Comment by parkycai** [comment]
测了两次必现，中间不需要暂停

**Comment by 2881099** [comment]
16 -> 17 段开 wifi 相隔1分多钟才输出日志

**Comment by parkycai** [comment]
> 16 -> 17 段开 wifi 相隔1分多钟才输出日志

是的，只要断开WIFI，就停住了，然后要过1分多钟才会抛出Exception，我用的是macOS 10.14，暂时没有试过别的操作系统。

**Comment by 2881099** [comment]
把完整测试代码贴出来，等会用你的代码我再试几次

**Comment by parkycai** [comment]
```
    public class Program
    {
        public static void Main(string[] args)
        {
            TestRedis_csredis();
            Console.ReadKey();
        }

        private static async Task TestRedis_csredis()
        {
            try
            {
                var client = new CSRedisClient("192.168.10.40:6379,password=foo:bared,defaultDatabase=1");
                RedisHelper.Initialization(client,null,null);
                RedisHelper.Subscribe(("Test", arg => Console.WriteLine($"[{DateTime.Now.ToLongTimeString()}]{arg.Body}")));
                for (int i = 0; i < 100; i++)
                {
                    try
                    {
                        Console.WriteLine($"[{DateTime.Now.ToLongTimeString()}]pub {i}--");
                        await client.PublishAsync("Test", $"Test{i}**");
                        Console.WriteLine($"[{DateTime.Now.ToLongTimeString()}]---------");
                        await Task.Delay(200);
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine($"[{DateTime.Now.ToLongTimeString()}]{ex}");
                    }
                }
                
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
```

**Comment by 2881099** [comment]
[测试视频，请查看-->>](https://files.cnblogs.com/files/kellynic/testcsredis.gif)

redis-server在是局域网另一台机器上。


测试了好几次没发现问题，我知道的是win控制台程序运行的时候，如果不小心选中了内容，会导致程序等待无响应。

我没有mac没有环境，mac的控制台程序运行中，如果选中内容，是不是也会卡死程序。

**Comment by parkycai** [comment]
应该不是选中了控制台内容的问题，加了poolStatics输出之后显示的是这样，仍然卡死：
![image](https://user-images.githubusercontent.com/22512293/46590798-e6e83080-cae8-11e8-8f80-b8d61bac8ae1.png)
