### ISSUE TITLE
CSRedis.RedisClientException: Connection was not opened 在 Quartz.net 中使用

### ISSUE THREAD

**Issue by herson-he** [2881099/csredis#370]
Describe：Quartz.net，任务调度中每隔5分钟，从数据库读取排行榜写到Redis中，偶尔会报上面的的异常，报了异常之后伴随着CPU 100%，CPU 100%这个问题目前还没有追踪到是不是这个异常引起的。

CSRedis Version：3.6.5

Redis Version: 6.0.10

Code：   
`RedisHelper.HSet(redisKey, "value", versionContent);
RedisHelper.HSet(redisKey, "version", giftbagVersionJson.Version);`

Environment: linux / Docker / NET5.0 

Config：192.168.0.64:6379,password=,idleTimeout=20000,poolsize=10,defaultDatabase=0,preheat=5,tryit=2,prefix=whby_

Exception：
2021-02-07 09:55:05.5039||ERROR|Quartz.Core.JobRunShell|Job group1.job1 threw an unhandled Exception:  CSRedis.RedisClientException: Connection was not opened
   at CSRedis.CSRedisClient.GetAndExecuteAsync[T](RedisClientPool pool, Func`2 handerAsync, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalarAsync[T](String key, Func`3 handerAsync)
   at WHGame.Business.Admin.Manage.RankingListManage.CreateRankingList()
   at WHGame.Business.Admin.Jobs.GenerateRankingListJob.Execute(IJobExecutionContext context)
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2021-02-07 09:55:05.5067||ERROR|Quartz.Core.ErrorLogger|Job group1.job1 threw an exception. Quartz.SchedulerException: Job threw an unhandled exception.
 ---> CSRedis.RedisClientException: Connection was not opened
   at CSRedis.CSRedisClient.GetAndExecuteAsync[T](RedisClientPool pool, Func`2 handerAsync, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalarAsync[T](String key, Func`3 handerAsync)
   at WHGame.Business.Admin.Manage.RankingListManage.CreateRankingList()
   at WHGame.Business.Admin.Jobs.GenerateRankingListJob.Execute(IJobExecutionContext context)
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: CSRedis.RedisClientException: Connection was not opened
   at CSRedis.CSRedisClient.GetAndExecuteAsync[T](RedisClientPool pool, Func`2 handerAsync, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalarAsync[T](String key, Func`3 handerAsync)
   at WHGame.Business.Admin.Manage.RankingListManage.CreateRankingList()
   at WHGame.Business.Admin.Jobs.GenerateRankingListJob.Execute(IJobExecutionContext context)
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]

**Comment by 2881099** [comment]
网络正常吗

**Comment by herson-he** [comment]
网络正常，其他的线程（同一个项目中）可以连redis。

**Comment by herson-he** [comment]
不是必须，偶尔出现。

**Comment by zhulj** [comment]
> CSRedis Version：3.6.5
> 
> Redis Version: 6.0.10
> 
> Environment: linux / Docker / NET5.0
> 
> Config：192.168.0.64:6379,password=,idleTimeout=20000,poolsize=10,defaultDatabase=0,preheat=5,tryit=2,prefix=whby_
> 
> 添加依赖：
> ` RedisHelper.Initialization(new CSRedisClient(Configuration["ConnectionStrings:RedisWeb"])); services.AddSingleton<IDistributedCache>(new Microsoft.Extensions.Caching.Redis.CSRedisCache(RedisHelper.Instance));`
> 
> 使用代码：
> ` await RedisHelper.HSetAsync(key, "Version", (int)Time.ConvertDateTimeInt(DateTime.Now)); await RedisHelper.HSetAsync(key, "RankingList", Text.JsonSerializer(listRankingList));`
> 
> Exception：
> 2021-02-07 09:55:05.5039||ERROR|Quartz.Core.JobRunShell|Job group1.job1 threw an unhandled Exception: CSRedis.RedisClientException: Connection was not opened
> at CSRedis.CSRedisClient.GetAndExecuteAsync[T](RedisClientPool pool, Func`2 handerAsync, Int32 jump, Int32 errtimes) at CSRedis.CSRedisClient.ExecuteScalarAsync[T](String key, Func`3 handerAsync)
> at WHGame.Business.Admin.Manage.RankingListManage.CreateRankingList()
> at WHGame.Business.Admin.Jobs.GenerateRankingListJob.Execute(IJobExecutionContext context)
> at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
> 2021-02-07 09:55:05.5067||ERROR|Quartz.Core.ErrorLogger|Job group1.job1 threw an exception. Quartz.SchedulerException: Job threw an unhandled exception.
> ---> CSRedis.RedisClientException: Connection was not opened
> at CSRedis.CSRedisClient.GetAndExecuteAsync[T](RedisClientPool pool, Func`2 handerAsync, Int32 jump, Int32 errtimes) at CSRedis.CSRedisClient.ExecuteScalarAsync[T](String key, Func`3 handerAsync)
> at WHGame.Business.Admin.Manage.RankingListManage.CreateRankingList()
> at WHGame.Business.Admin.Jobs.GenerateRankingListJob.Execute(IJobExecutionContext context)
> at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
> --- End of inner exception stack trace --- [See nested exception: CSRedis.RedisClientException: Connection was not opened
> at CSRedis.CSRedisClient.GetAndExecuteAsync[T](RedisClientPool pool, Func`2 handerAsync, Int32 jump, Int32 errtimes) at CSRedis.CSRedisClient.ExecuteScalarAsync[T](String key, Func`3 handerAsync)
> at WHGame.Business.Admin.Manage.RankingListManage.CreateRankingList()
> at WHGame.Business.Admin.Jobs.GenerateRankingListJob.Execute(IJobExecutionContext context)
> at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
> 
> Describe：Quartz.net，任务调度中每隔5分钟，从数据库读取排行榜写到Redis中，偶尔会报上面的的异常，异常之后该Job线程就无法连到Redis了，但是其他线程还是可以正常连接到Redis，读和写都没有问题，只有Quartz下的Job这个任务线程报这个异常。报了异常之后伴随着CPU 100%，CPU 100%这个问题目前还没有追踪到是不是这个异常引起的。
异常无法连接的问题，我之前是加了,abortConnect=false，就可以解决，你试试

**Comment by zhulj** [comment]
异常无法连接的问题，我之前是加了,abortConnect=false，就可以解决，你试试

**Comment by jsonzhuwei** [comment]
@herson-he 你好，问题解决了吗？
