### ISSUE TITLE
SafeObjectPool.Get 获取超时（10秒）。报这种问题怎么处理？

### ISSUE THREAD

**Issue by xiangxiren** [2881099/csredis#380]
at CSRedis.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)  
at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
at CSRedis.CSRedisClient.SetAsync(String key, Object value, TimeSpan expire, Nullable`1 exists)

**Comment by 2881099** [comment]
原因一：有没有自己使用过 RedisHelper.Instance.Nodes

原因二：PoolSize 设置过小，程序访问量过高

监视 RedisHelper.Instance.Nodes.First().Statistics，它的值：Pool: 5/100, Get wait: 0, GetAsync await: 0

```
5 为可用连接数，值为0后开始排队
100 为当前最大连接数
Get await 为同步方法获取连接的排队数量（超过10秒就会报错）
GetAsync await 为异步方法获取连接的排队数量
```

注意：尽量不要使用 RedisHelper.Instance.Nodes.First().Get() 或 GetAsync() 方法，否则请检查姿势。

**Comment by xiangxiren** [comment]
一、有使用过 RedisHelper.Instance.Nodes，用了RedisClient的public Task<object> EvalAsync(string script, string[] keys, params object[] arguments)。RedisHelper的Eval不支持多个key。但这里使用频次不高。
二、PoolSize 没有单独设置，默认值应该是50

**Comment by xiangxiren** [comment]
一、有使用过 RedisHelper.Instance.Nodes，用了RedisClient的public Task<object> EvalAsync(string script, string[] keys, params object[] arguments)。RedisHelper的Eval不支持多个key。但这里使用频次不高。
二、PoolSize 没有单独设置，默认值应该是50
