### ISSUE TITLE
版本3.6.6最新使用Lock锁方法内内容执行时间稍微长就会执行报错，对象被释放

### ISSUE THREAD

**Issue by bingtianyiyan** [2881099/csredis#389]
代码如下：
  public abstract class MyHelper1 : RedisHelper<MyHelper1> { }

使用：
   MyHelper1.Initialization(new CSRedisClient("127.0.0.1:6690,password=xxx"));

            using (MyHelper1.Lock($"MyTest", 2))
            {
                Task.Delay(100000).Wait();
                Console.WriteLine("eee");
            }

稍微停留下就会出错，降到版本3.6.5则正常

报错内容：使用前请初始化 RedisHelper.Initialization(new CSRedis.CSRedisClient("127.0.0.1:6379,pass=123,defaultDatabase=13,poolsize=50,ssl=false,writeBuffer=10240,prefix=key前辍"));

  at RedisHelper`1.get_Instance()
   at RedisHelper`1.Eval(String script, String key, Object[] args)
   at CSRedis.CSRedisClientLock.Refresh(Int32 milliseconds)
   at CSRedis.CSRedisClientLock.<>c__DisplayClass5_0.<.ctor>b__0(Object state2)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/Timer.cs:line 656
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 172
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/System.Private.CoreLib/shared/System/Threading/ExecutionContext.cs:line 200
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool) in /_/src/System.Private.CoreLib/shared/System/Threading/Timer.cs:line 649
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool) in /_/src/System.Private.CoreLib/shared/System/Threading/Timer.cs:line 600
   at System.Threading.TimerQueue.FireNextTimers() in /_/src/System.Private.CoreLib/shared/System/Threading/Timer.cs:line 286
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id) in /_/src/System.Private.CoreLib/src/System/Threading/Timer.CoreCLR.cs:line 61

**Comment by YahuiWong** [comment]
@2881099 你好 遇到了一样的问题    大佬 有修复的时间计划吗

**Comment by xwb2535** [comment]
var locks = RedisContext.Lock("getIds:" + code, 4, true);
            using (locks)
            {}

外面的方法加了try catch ，

在linux的docker容器里面，压测的时候，运行够快，但是异常并没有被捕获，而是直接中断了我的容器应用，十分怪哉。
一秒钟请求230次访问。
Unhandled exception. System.Exception: 使用前请初始化 RedisHelper.Initialization(new CSRedis.CSRedisClient("127.0.0.1:6379,pass=123,defaultDatabase=13,poolsize=50,ssl=false,writeBuffer=10240,prefix=key前辍"));


   at RedisHelper`1.get_Instance()


   at RedisHelper`1.Eval(String script, String key, Object[] args)


   at CSRedis.CSRedisClientLock.Refresh(Int32 milliseconds)


   at CSRedis.CSRedisClientLock.<>c__DisplayClass5_0.<.ctor>b__0(Object state2)


   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)


   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)


--- End of stack trace from previous location ---


   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)


   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)


   at System.Threading.TimerQueue.FireNextTimers()

**Comment by bingtianyiyan** [comment]
来信已收到，我会尽快回复，杨
