### ISSUE TITLE
stream XPending 报错：Unexpected response type: MultiBulk (expecting Bulk)

### ISSUE THREAD

**Issue by a815952553** [2881099/csredis#421]
单元测试 入参如下：rds.XPending("testXReadGroupKey01", "testXReadGroup01","-","+",100);
报错代码：
public void ExpectType(RedisMessage expectedType)
        {
            RedisMessage type = ReadType();
            if ((int)type == -1)
            {
                var alldata = _io.ReadAll();
                try { _io.Dispose(); } catch { }
                throw new EndOfStreamException($"Unexpected end of stream; expected type '{expectedType}'; data = '{Encoding.UTF8.GetString(alldata)}'");
            }
            if (type != expectedType)
                throw new RedisProtocolException($"Unexpected response type: {type} (expecting {expectedType})");
        }

**Comment by 2881099** [comment]
换用 freeredis，新命令支持好一些

**Comment by BenLocal** [comment]
我也遇到了相同的问题，想问下csredis.core后面这个问题会修复吗？
```
            var streamsEntries = _redisClient.XPending(key,
                    consumerGroup,
                    start: "-",
                    end: "+",
                    count: _options.StreamEntriesCount,
                    consumer: consumerGroup);
```

Exception：

```
csreids 错误【localhost:6379/0】：Unexpected response type: MultiBulk (expecting Bulk)    at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.XPending(String key, String group, String start, String end, Int64 count, String consumer)
```

**Comment by BenLocal** [comment]
freeredis的nuget包现在只支持到.net5，大概什么时候支持到.net6

**Comment by 2881099** [comment]
> freeredis的nuget包现在只支持到.net5，大概什么时候支持到.net6

支持 netstandard 20 啊
