### ISSUE TITLE
求助： Redis 集群在set  key的时候，某些key包含中文就会出现这个问题，这是什么原因？

### ISSUE THREAD

**Issue by yangxu-sky** [2881099/csredis#437]
exception: CSRedis.RedisException: MOVED 5541 xxxx:6379.    
   at CSRedis.Internal.IO.RedisReader.ReadType()
   at CSRedis.Internal.Commands.RedisStatus.Nullable.Parse(RedisReader reader)
   at CSRedis.Internal.RedisConnector.CallAsync[T](RedisCommand`1 command)
   at CSRedis.RedisClient.WriteAsync[T](RedisCommand`1 command)
   at CSRedis.CSRedisClient.SetAsync(String key, Object value, TimeSpan expire, Nullable`1 exists)

**Comment by yangxu-sky** [comment]
@[2881099](https://github.com/2881099)
麻烦帮忙看看

**Comment by 2881099** [comment]
MOVED 5541 xxxx:6379.

这个是集群错误

**Comment by xuyangxy** [comment]
> MOVED 5541 xxxx:6379.
> 
> 
> 
> 这个是集群错误

能详细说说吗，我们也猜测是集群问题，在aws也尝试重新建过集群，依然会出现这个问题。我们的集群是两主两备的。

**Comment by 2881099** [comment]
如果是云服务器，当它是单机访问就行，把 testCluster=false 设置一下
