### ISSUE TITLE
连接阿里云分片集群时，无法自动进行分片切换，调试源码发现是无法找到Slot，麻烦帮忙分析下原因

### ISSUE THREAD

**Issue by binjinshi123** [2881099/csredis#455]
代码位置：var slot = GetClusterSlot(string.Concat(prefix, key)); //redis-cluster 模式，选取第一个 connectionString prefix 前辍求 slot

**Comment by 2881099** [comment]
阿里云的集群，用起来和单机版本体验一样。

连接时，使用单机版本连接串。把 testcluster=false 设置一下

**Comment by binjinshi123** [comment]
HSetAsync 会报这个错误
2022-08-19 11:38:25.5257|VTS.MS.Common.LogHelper|INFO|[MoveXHData]insert into Redis error, userid:88 System.AggregateException: One or more errors occurred. (Value cannot be null.
Parameter name: key) ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNullException()
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at CSRedis.CSRedisClient.ExecuteScalarAsync[T](String key, Func`3 handerAsync) in F:\工作目录\VTS.STP\cssharp\VTS.MS\CsRedisCore\CSRedisClientAsync.cs:line 344
   at VTS.MS.Reckoning.Service.Redis.RedisOper.HSetAsync[T](String key, String field, T value) in F:\工作目录\VTS.STP\cssharp\VTS.MS\VTS.MS.Reckoning.Service\Redis\RedisOper.cs:line 47
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at VTS.MS.Reckoning.Service.SettleOutService.WriteSingleAccount(XH_CapitalAccount xH_Capital, List`1 xH_AccountHolds, List`1 listStock, List`1 listShare, List`1 hK_AccountHolds, List`1 listOtcAccount, List`1 listOtcFundAccount) in F:\工作目录\VTS.STP\cssharp\VTS.MS\VTS.MS.Reckoning.Service\Service\SettleOutService.cs:line 510
   at VTS.MS.Reckoning.Service.SettleOutService.<>c__DisplayClass8_1.<WirteAccountInfoList>b__4(Int64 item) in F:\工作目录\VTS.STP\cssharp\VTS.MS\VTS.MS.Reckoning.Service\Service\SettleOutService.cs:line 162
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNullException()
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at CSRedis.CSRedisClient.ExecuteScalarAsync[T](String key, Func`3 handerAsync) in F:\工作目录\VTS.STP\cssharp\VTS.MS\CsRedisCore\CSRedisClientAsync.cs:line 344
   at VTS.MS.Reckoning.Service.Redis.RedisOper.HSetAsync[T](String key, String field, T value) in F:\工作目录\VTS.STP\cssharp\VTS.MS\VTS.MS.Reckoning.Service\Redis\RedisOper.cs:line 47<---

**Comment by 2881099** [comment]
System.ArgumentNullException: Value cannot be null.

System.Collections.Concurrent.ConcurrentDictionary2.ThrowKeyNullException() at System.Collections.Concurrent.ConcurrentDictionary2.TryGetValue(TKey key, TValue& value)

检查字典的参数

**Comment by binjinshi123** [comment]
![CSRedisClient](https://user-images.githubusercontent.com/111546529/185545069-8a29cde5-ecb3-4630-bb2f-1acdd90a6ff3.png)

**Comment by 2881099** [comment]
不要用集群模式啊，用单机模式

**Comment by 2881099** [comment]
2楼已经回复你了，阿里云集群是魔改的定制版本。

**Comment by binjinshi123** [comment]
> 2楼已经回复你了，阿里云集群是魔改的定制版本。

我试下单机模式

**Comment by 2881099** [comment]
testcluster=false 连接串加上这个
