### ISSUE TITLE
高流量下经常连接超时，但redis监控正常

### ISSUE THREAD

**Issue by ashuai** [2881099/csredis#478]
## csreids 错误
csreids 错误【xxx.redis.rds.aliyuncs.com:6379/0】：Connect to server timeout    at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Get(String key)

### connectionstring
xxx.redis.rds.aliyuncs.com:6379,password=xxx,abortConnect=false,testcluster=false,idleTimeout=30000,tryit=1,poolsize=30,preheat=10,syncTimeout=3000,connectTimeout=3000,asyncPipeline

**实例规格 0.5c 512m, 16并发**

## redis实例诊断
![image](https://user-images.githubusercontent.com/76211/234763595-24e2425f-c26f-4d4b-affc-638221c89e74.png)

------

请问这大概可能是哪方面的问题？

**Comment by 2881099** [comment]
客户端连接超时，说明请求没打到服务器，服务器又怎么会有日志记录？

**Comment by xiaolei000129** [comment]
我也出现了，你解决了吗？
