### ISSUE TITLE
最近几天老是0点后一段时间 redis都报 MISCONF Redis is configured to save RDB snapshots

### ISSUE THREAD

**Issue by apgk** [2881099/csredis#490]
1. 本机磁盘容量够
2. 本机16G内存大概剩余800M-1G
3. 目前做法 根据百度的 把 那个 stop-writes-on-bgsave-error 从yes 设置为no 
4. 2023-11-04 设置过 通过 config set  然后重启，昨天和今天凌晨又发生了以下错误。
完整的异常信息
System.Exception: 【127.0.0.1:6379/13】状态不可用，等待后台检查程序恢复方可使用。MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Command: PING 
 ---> CSRedis.RedisException: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
Command: PING 
 ---> CSRedis.RedisException: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
   at CSRedis.Internal.IO.RedisReader.ReadType()
   at CSRedis.Internal.IO.RedisReader.ExpectType(RedisMessage expectedType)
   at CSRedis.Internal.IO.RedisReader.ReadStatus(Boolean checkType)
   at CSRedis.Internal.Commands.RedisStatus.Parse(RedisReader reader)
   at CSRedis.Internal.RedisConnector.Call[T](RedisCommand`1 command)
   --- End of inner exception stack trace ---
   at CSRedis.Internal.RedisConnector.Call[T](RedisCommand`1 command)
   at CSRedis.RedisClient.Write[T](RedisCommand`1 command)
   at CSRedis.RedisClient.Ping()
   at CSRedis.RedisClientPool.Return(Object`1 obj, Exception exception, Boolean isRecreate)
   --- End of inner exception stack trace ---
   at CSRedis.Internal.ObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
   at CSRedis.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Get[T](String key)
   at RedisHelper`1.Get[T](String key)

**Comment by 2881099** [comment]
redis-for-windows 么？

**Comment by apgk** [comment]
> redis-for-windows 么？

是的 x64 3.2版本
已经持续好久没出现这个问题了，上回出现还是 硬盘全满了。

**Comment by chunjieyaya** [comment]
> > redis-for-windows 么？
> 
> 是的 x64 3.2版本 已经持续好久没出现这个问题了，上回出现还是 硬盘全满了。

没考虑升级redis版本吗？

**Comment by apgk** [comment]
> > > redis-for-windows 么？
> > 
> > 
> > 是的 x64 3.2版本 已经持续好久没出现这个问题了，上回出现还是 硬盘全满了。
> 
> 没考虑升级redis版本吗？

稳住了升级啥。。。。
