### ISSUE TITLE
3.0及3.0以后的版本，报错。状态不可用，等待后台检查程序恢复方可使用。Unexpected end of stream; 

### ISSUE THREAD

**Issue by billsking** [2881099/csredis#52]
System.Exception: 【127.0.0.1:6379/0】状态不可用，等待后台检查程序恢复方可使用。Unexpected end of stream; expected type 'Status'
   at SafeObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
   at SafeObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Get(String key)
   at RedisHelper.Get(String key)

3.0以前的版本没问题。

**Comment by 2881099** [comment]
追溯一下错误（第一次发生错误的日志）

**Comment by 2881099** [comment]
只有 ping 出错，才会走向这个逻辑。

**Comment by 2881099** [comment]
```csharp
public void Return(Object<RedisClient> obj, Exception exception, bool isRecreate = false) {
	if (exception != null) {
		try {
			obj.Value.Ping();

			var fcolor = Console.ForegroundColor;
			Console.WriteLine($"");
			Console.ForegroundColor = ConsoleColor.DarkYellow;
			Console.WriteLine($"csreids 错误【{Policy.Name}】：{exception.Message} {exception.StackTrace}");
			Console.ForegroundColor = fcolor;
			Console.WriteLine($"");

		} catch(Exception ex) {
			base.SetUnavailable(ex);
		}
	}
	base.Return(obj, isRecreate);
}
```

```csharp
public void OnGet(Object<RedisClient> obj) {
	if (_pool.Encoding != obj.Value.Encoding) obj.Value.Encoding = _pool.Encoding;
	if (_pool.IsAvailable) {
		if (DateTime.Now.Subtract(obj.LastReturnTime).TotalSeconds > 60 || obj.Value.IsConnected == false) {
			try {
				obj.Value.Ping();
			} catch(Exception ex) {
				obj.ResetValue();
				if (_pool.SetUnavailable(ex) == true)
					throw new Exception($"【{this.Name}】状态不可用，等待后台检查程序恢复方可使用。{ex.Message}");
			}
		}
	}

}

async public Task OnGetAsync(Object<RedisClient> obj) {
	if (_pool.Encoding != obj.Value.Encoding) obj.Value.Encoding = _pool.Encoding;
	if (_pool.IsAvailable) {
		if (DateTime.Now.Subtract(obj.LastReturnTime).TotalSeconds > 60 || obj.Value.IsConnected == false) {
			try {
				await obj.Value.PingAsync();
			} catch (Exception ex) {
				obj.ResetValue();
				if (_pool.SetUnavailable(ex) == true)
					throw new Exception($"【{this.Name}】状态不可用，等待后台检查程序恢复方可使用。{ex.Message}");
			}
		}
	}
}
```

**Comment by 2881099** [comment]
如果可以，把所有相关日志上传一下

**Comment by billsking** [comment]
我晚点发上来。我再描述下情况。 我是服务启动后，大概能正常运行十几分钟，然后再报这个错误。也就是说，刚开始是可以正常启动的。但运行几分钟后，就会报错，期间没有出现大的访问量，就几个测试人员。所以我怀疑是csredis代码的问题。

**Comment by billsking** [comment]
System.Exception: 【127.0.0.1:6379/0】状态不可用，等待后台检查程序恢复方可使用。Unexpected end of stream; expected type 'Status'
   at CSRedis.RedisClientPoolPolicy.OnGet(Object`1 obj)
   at SafeObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Set(String key, Object value, Int32 expireSeconds, Nullable`1 exists)
   at RedisHelper.Set(String key, Object value, Int32 expireSeconds, Nullable`1 exists)
   at Hy.Business.LoginServices.GenerateToken(Employee userModel, JwtParam jwtParam, String ip, String platform, Boolean isLog) in E:\code\huoyan\Hy.Api\LoginServices.cs:line 51
   at Hy.Business.Controllers.EmployeeController.Login(EmpLoginDto dto) in E:\code\huoyan\Hy.Api\Controllers\EmployeeController.cs:line 66
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync() 

这是详细的错误信息。程序启动后是正常的， 大概运行十几分钟吧，再访问就报错了。 csredis好像是没有监听状态的事件吧，我没找到相关代码，所以也不知道具体什么时候报的错，所有的报错信息都是和上面一样的。请大神检查。

**Comment by 2881099** [comment]
每次执行前检查可用性，最好能把所有日志打包后发出来

**Comment by 2881099** [comment]
这个错误的原因我很清楚，语言日志查明原因。我这边试不出这个bug

**Comment by billsking** [comment]
[2018-11-04.log](https://github.com/2881099/csredis/files/2545738/2018-11-04.log)
所有的日志也看不出什么问题来。

**Comment by billsking** [comment]
这个有没有可能跟我的redis服务端有关系？

**Comment by 2881099** [comment]
一整天的日志怎么只有几条，不关redis-server事的

**Comment by billsking** [comment]
这个是专门部署测试的， 不是生产环境。   我只记录了error日志，没有其他日志。而且，这个就没法跑一整天，我测试好几次了。 发布后，是正常的。  然后我就没再关了。也没访问了。  过了10分钟左右， 再访问就出现这个问题了。。

**Comment by 2881099** [comment]
之前也有这个判断，目的是防止服务端重启，或者网络断开后出错。

如果ping服务器返回的不正确，说明socket数据可能错乱了

**Comment by 2881099** [comment]
追问一下，环境是本地windows吗，redis-server是远程还是本地

**Comment by billsking** [comment]
服务器是centos，redis-server本地远程都试过。都有问题。 然后我用的web服务器是jexus

**Comment by 2881099** [comment]
有一个用户redis-server配置了，链接活动时间超过多久，服务端主动断开，这个客户端无法监测所以增加的这个60秒判断

**Comment by 2881099** [comment]
再追问一下，出错这个错误后，继续访问会恢复访问吗？

**Comment by billsking** [comment]
应该是属于恢复访问。 我服务启动后，就访问了一两次。 然后就没有任何访问了。   过了十几分钟后再访问就会出现这个问题。

**Comment by 2881099** [comment]
恢复逻辑貌似确实有问题，v3.0.17 nuget 发布中，改成和原来一样了。

待会试试。

**Comment by 2881099** [comment]
@kuiyu 应用与redis-server网络不通，才会出这个错误。

**Comment by 2881099** [comment]
@kuiyu 另外，这个是用于防止意外断开后，恢复机制。

执行出错后，将检查网络是否可用，若不可用则将整个 CSRedisClient 状态设置成不可用，再使用时会报上述错误。

恢复机制，出现上述状态后，后台启用新线程，定时5秒检查网络，直至正常后状态恢复。
状态恢复成功后，再使用就不会报这个错误了。

**Comment by 2881099** [comment]
@kuiyu 建议做一个监控接口，大致代码如下：

```cscharp
[HttpGet("connection/redis")]
public ContentResult Get_connection_redis() {
	var sb = new StringBuilder();
	foreach(var pool in RedisHelper.Nodes.Values) {
		sb.AppendLine($@"【{pool.Policy.Name}】　　状态：{(pool.IsAvailable ? "正常" : $"[{pool.UnavailableTime}] {pool.UnavailableException.Message}")}
-------------------------------------------------------------------------------------------------------
Slots：{RedisHelper.Instance.SlotCache.Count}/16384, {pool.StatisticsFullily}
");
	}
	return new ContentResult { ContentType = "text/plan;charset=utf-8", Content = sb.ToString() };
}
```

![image](https://user-images.githubusercontent.com/16286519/49437477-934b4800-f7f6-11e8-90d7-e4ebb23ca621.png)

Pool: 20/20，为正常状态，前面是可用连接数量，后面是最大连接数量

**Comment by kuiyu** [comment]
问题己找到，是连接字符串问题

**Comment by zsy619** [comment]
> 问题己找到，是连接字符串问题

麻烦发下链接字符串，是什么情况，我也遇到了

**Comment by wt5wt** [comment]
> 
> 
> > 问题己找到，是连接字符串问题
> 
> 麻烦发下链接字符串，是什么情况，我也遇到了

请问是什么问题，我也遇到了，下面是我的连接字符串

xxxxxxx.org:8568,password=xxxxxx,defaultDatabase=8,poolsize=300,testcluster=false,writeBuffer=30690,tryit=2

**Comment by 2881099** [comment]
> > > 问题己找到，是连接字符串问题
> > 
> > 
> > 麻烦发下链接字符串，是什么情况，我也遇到了
> 
> 状态不可用，等待后台检查程序恢复方可使用。Connect to server timeout
> 
> 我碰到的情况是 超时
> 
> xxxxxxx.org:8568,password=xxxxxx,defaultDatabase=8,poolsize=300,testcluster=false,writeBuffer=30690,tryit=2

增加配置试试：preheat=1,idleTimeout=15000

**Comment by 2881099** [comment]
@wt5wt

**Comment by wt5wt** [comment]
> 
> 
> @wt5wt

好的 ，谢谢

**Comment by liuyl1992** [comment]
背景：
本地windwos下调试没任何异常，只在k8s下的linux 环境后台会一直记录 状态不可用，其实可用状态是没问题的

同样的 问题，模式用的集群，不管所有节点都加入连接字符串还是按照说明只放一个，其他自动加入，后台日志都会报错：
```
仍然不可用，下一次恢复检查时间：05/27/2020 13:57:04，错误：(Unexpected response type: 72 (expecting Status))
```
还有另一个现象是：
虽然后台会记录以上错误，但是除了几个key之外不影响正常的set /get 调用操作

特殊情况：
实际发现有个别数字的key进行get操作(不管key存不存在)，始终报以下异常，而且同样的，本地是没问题的
```System.Exception: 【172.16.127.15:7001/0】状态不可用，等待后台检查程序恢复方可使用。Unexpected response type: 72 (expecting Status)
 ---> CSRedis.RedisProtocolException: Unexpected response type: 72 (expecting Status)
   at CSRedis.RedisClientPool.<>c__DisplayClass0_0.<.ctor>b__0(Object s, EventArgs o)
   at CSRedis.RedisClientPoolPolicy.<>c__DisplayClass60_0.<OnCreate>b__0(Object s, EventArgs o)
   at CSRedis.RedisClient.OnConnectionConnected(Object sender, EventArgs args)
   at CSRedis.Internal.RedisConnector.OnConnected()
   at CSRedis.Internal.RedisConnector.Connect(Int32 timeout)
   at CSRedis.RedisClient.Connect(Int32 timeout)
   at CSRedis.RedisClientPool.Return(Object`1 obj, Exception exception, Boolean isRecreate)
   --- End of inner exception stack trace ---
   at CSRedus.Internal.ObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
   at CSRedus.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Get[T](String key)
   at RedisHelper`1.Get[T](String key)
```
有问题的key在k8s上的linux始终都返回异常，不是随机发生，是固定的key，即使key不存在于redis

**Comment by 2881099** [comment]
@liuyl1992 这个是类型错误，如果 key 是 string，你用 hash 命令操作就会这样

**Comment by liuyl1992** [comment]
> @liuyl1992 这个是类型错误，如果 key 是 string，你用 hash 命令操作就会这样

用的get命令，而且本地windows下执行是没一点问题的，而且后台日志也不会检测到不可用，另一点表现是只有个别key在部署的机器上执行get会以上报错，并不是所有key都不行

**Comment by 2881099** [comment]
@liuyl1992 你没明白我说的意思，测试服那个 key 类型可以 get，所以正常。正式服出错是数据问题，他是提示类型错误，比如这个 key 的类型是 hash 你用 get key 肯定就出错了

**Comment by liuyl1992** [comment]
> @liuyl1992 你没明白我说的意思，测试服那个 key 类型可以 get，所以正常。正式服出错是数据问题，他是提示类型错误，比如这个 key 的类型是 hash 你用 get key 肯定就出错了

其实在服务器上get操作的key并没插入过，本地获取同一个key只是返回null，本地和服务器公用的一个redis server的

**Comment by liuyl1992** [comment]
目前基本排查出问题，不是驱动的问题，是服务器环境的问题
