### ISSUE TITLE
Unexpected response type: Int (expecting Bulk) 请问这个问题还会解决吗?

### ISSUE THREAD

**Issue by jakey188** [2881099/csredis#520]
请问这个问题还会解决吗

CSRedis.RedisProtocolException: Unexpected response type: Int (expecting Bulk)
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.XInfoGroups(String key)

CSRedisCore:3.8.803

Redis Version : 7.2.3

**Comment by 2881099** [comment]
建议过渡到 FreeRedis
