### ISSUE TITLE
Windows上打的redis集群，端口数是16384，其中一台机器会出现System.Net.Sockets.SocketException (0x80004005): 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作

### ISSUE THREAD

**Issue by haifengwang** [2881099/csredis#67]
使用方式：
```
            var csredis = new CSRedis.CSRedisClient(null, Configuration.GetValue<string>("ConnectionStrings:RedisConnectionString"));
            //初始化 RedisHelper
            RedisHelper.Initialization(csredis);
            //注册mvc分布式缓存
            services.AddSingleton<IDistributedCache>(new Microsoft.Extensions.Caching.Redis.CSRedisCache(RedisHelper.Instance));
//RedisConnectionString "    "xx.1.xxx.114:6379,defaultDatabase=0,poolsize=50,preheat=true,ssl=false,writeBuffer=10240"
```
ip是集群的一个主节点

在某时间段会出现：由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。

> System.Net.Sockets.SocketException (0x80004005): 由于系统缓冲区空间不足或队列已满，不能执行套接字上的操作。
>    at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump)
>    at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump)
>    at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
>    at CSRedis.CSRedisClient.Get[T](String key)
>    at RedisHelper.Get[T](String key)

请大神帮分析一下属于什么问题，感谢

**Comment by 2881099** [comment]
请问使用的什么版本

**Comment by haifengwang** [comment]
Caching.CSRedis 3.0.25

**Comment by haifengwang** [comment]
> 请问使用的什么版本

Caching.CSRedis 3.0.25

**Comment by 2881099** [comment]
这个版本没有对应的改动，错误原因是windows资源不足，需要具体对环境分析了。

1、内存占用情况
2、poolsize 值
3、redis-server 上 client list 连接数实际值
4、netstat 查看端口占用情况
5、错误发生的频率（多久发生）
6、调大虚拟内存

**Comment by 2881099** [comment]
暂时想到的是这些，如果有条件还是上 linux 系统吧

**Comment by skyxing1207** [comment]
netstat 查看端口占用情况
发现端口占用数很大。达到最大连接数，导致连接失败，这是什么原因导致。
错误提示
ERR max number of clients reached
   at CSRedis.Internal.IO.RedisReader.ReadType()
   at CSRedis.Internal.IO.RedisReader.ExpectType(RedisMessage expectedType)
   at CSRedis.Internal.IO.RedisReader.ReadStatus(Boolean checkType)
   at CSRedis.Internal.Commands.RedisStatus.Parse(RedisReader reader)
   at CSRedis.Internal.RedisConnector.Call[T](RedisCommand`1 command)
   at CSRedis.RedisClient.Write[T](RedisCommand`1 command)
   at CSRedis.RedisClient.Auth(String password)
   at CSRedis.ConnectionPool.<.ctor>b__26_0(Object s, EventArgs o)
   at CSRedis.RedisClient.OnConnectionConnected(Object sender, EventArgs args)
   at CSRedis.Internal.RedisConnector.OnConnected()
   at CSRedis.Internal.RedisConnector.Connect(Int32 timeout)
   at CSRedis.Internal.RedisConnector.ConnectIfNotConnected()
   at CSRedis.Internal.RedisConnector.Call[T](RedisCommand`1 command)
   at CSRedis.RedisClient.Write[T](RedisCommand`1 command)
   at CSRedis.RedisClient.Exists(String key)
   at CSRedis.CSRedisClient.<>c.<Exists>b__27_0(RedisConnection2 c, String k)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Exists(String key)
   at RedisHelper.Exists(String key)
   at Acadsoc.Cache.CSRedisCache.KeyExists(String key) in D:\Projects\Acadsoc\Acadsoc.Microservice\src\Acadsoc.Cache\CSRedisCache.cs:line 45
   at Acadsoc.Cache.RedisCacheManager.IsSet(String key) in D:\Projects\Acadsoc\Acadsoc.Microservice\src\Acadsoc.Cache\RedisCacheManager.cs:line 130
   at Acadsoc.Cache.CacheExtensions.GetAsync[T](ICacheManager cacheManager, String key, Func`1 acquire, Int32 cacheTime, String keyStoredGroup) in D:\Projects\Acadsoc\Acadsoc.Microservice\src\Acadsoc.Cache\Extensions.cs:line 52
   at Acadsoc.XXX.Service.Platform.MarketingPlatformService.GetAllPlatformListAsync() in D:\Projects\Acadsoc\Acadsoc.Microservice\src\Acadsoc.XXX.Service\Platform\MarketingPlatformService.cs:line 60

**Comment by 2881099** [comment]
用的单例吗

**Comment by skyxing1207** [comment]
public static CSRedisClient Instance
  {
    get
    {
      if (RedisHelper._instance == null)
        throw new Exception("使用前请初始化 RedisHelper.Initialization(new CSRedis.CSRedisClient(\"127.0.0.1:6379,pass=123,defaultDatabase=13,poolsize=50,ssl=false,writeBuffer=10240,prefix=key前辍\");");
      return RedisHelper._instance;
    }
  }
这样使用的，算是单例吧。

**Comment by 2881099** [comment]
1、这样写不严谨，如果是并发的情况下会创建很多个实例。可以考虑用 Lazy 控制，或者在程序启动的时候执行 RedisHelper.Initialization。

2、您是把源码嵌进项目进行开发的吧？建议升级到最新。
