### ISSUE TITLE
Unable to write data to the transport connection: 远程主机强迫关闭了一个现有的连接。

### ISSUE THREAD

**Issue by taylor1102** [2881099/csredis#70]
System.IO.IOException: Unable to write data to the transport connection: 远程主机强迫关闭了一个现有的连接。. ---> System.Net.Sockets.SocketException: 远程主机强迫关闭了一个现有的连接。
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Exists(String key)
   at RedisHelper.Exists(String key)

**Comment by 2881099** [comment]
连接被服务器关闭了，想必是远程连接的redis-server。
程序运行多久出现

**Comment by taylor1102** [comment]
程序运行一两个小时就会出现，服务器只有一台啊~

**Comment by 2881099** [comment]
把环境和问题一次描述清楚

**Comment by taylor1102** [comment]
windows服务器IIS，.net core2.1
之前用EF的时候redis不会有问题，.net core2.0
昨天把EF换成Dapper就会一直有这个错：远程主机强迫关闭了一个现有的连接。.net core2.1


记录时间：2018-12-19 11:02:56,883
线程ID：84
日志等级：ERROR
日志类型：Robin.Hlb.Services.Provider.GlobalExceptionFilter
Error
*——*——*——*——*——*——E n d——*——*——*——*——*——*
System.IO.IOException: Unable to write data to the transport connection: 远程主机强迫关闭了一个现有的连接。. ---> System.Net.Sockets.SocketException: 远程主机强迫关闭了一个现有的连接。
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Exists(String key)
   at RedisHelper.Exists(String key)
   at Robin.Hlb.Services.RedisService.GetIndexByCategory() in F:\Hlb\Services\RedisService.cs:line 71
   at Robin.Hlb.Web.Controllers.HomeController.Index(Int32 page) in F:\Hlb\Web\Controllers\HomeController.cs:line 61
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()

**Comment by taylor1102** [comment]
用的是大米云，监控带宽也没超，就是内存一直比较高80以上（装了elasticsearch 占的多）

**Comment by 2881099** [comment]
1、IIS回收那个功能关掉没有
2、csredis 报错和 ef dapper 有什么关联
3、在出现此错误后，程序是退出了，还是继续报错，或者多久后能恢复

**Comment by 2881099** [comment]
检查一下redis日志，有没有重启过

**Comment by 2881099** [comment]
redis-server 的日志

**Comment by 2881099** [comment]
因为错误比较明显，提示＂远程主机强迫关闭了一个现有的连接＂，这是被迫行为

**Comment by taylor1102** [comment]
回收内存一直都有设置没动过，昨天把redis提取写了个service类 用了core 自带的注入就出现这个问题了

**Comment by 2881099** [comment]
看看怎么注入的

**Comment by taylor1102** [comment]
services.AddSingleton(Configuration)
                .AddTransient<IRedisService, RedisService>()
                .AddTransient<IUserInfoService, UserInfoService>();

            services.AddOptions();
            services.AddMvc(option =>
            {
                option.Filters.Add(new GlobalExceptionFilter());
            })
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
                .AddControllersAsServices();
            return AspectCoreContainer.BuildServiceProvider(services);

--------------------------------------------------------------------------------------------------------
    public class RedisService : MySqlProvider, IRedisService
    {
        #region 友链缓存
        public List<Links> GetLinks()
        {
            string redisurl = ConfigHelper.GetConfigurationValue("ConnectionStrings", "Redis");
            var csredis = new CSRedis.CSRedisClient(redisurl);
            //初始化 RedisHelper
            RedisHelper.Initialization(csredis);
            if (RedisHelper.Exists("links"))
            {
                return JsonConvert.DeserializeObject<List<Links>>(RedisHelper.Get("links"));
            }
            else
            {
                using (var conn = GetOpenConnection())
                {
                    string sql = @"select * from Links order by sort asc";
                    var list = conn.Query<Links>(sql).ToList();
                    RedisHelper.Set("links", JsonConvert.SerializeObject(list), 1296000);
                    return list;
                }
            }
        }
        #endregion
.....

**Comment by 2881099** [comment]
csredis不能这样使用，采用单例注入吧

**Comment by 2881099** [comment]
RedisHelper.CacheShell 这个方法了解一下

**Comment by taylor1102** [comment]
嗯 ，我试试 谢谢~
