### ISSUE TITLE
DelAsync 多key删除，跨slot报错

### ISSUE THREAD

**Issue by MichaelRWP** [2881099/csredis#92]
异常信息：
StackTrace:	
at CSRedis.CSRedisClient.GetAndExecuteAsync[T](RedisClientPool pool, Func`2 handerAsync, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteNonQueryAsync(String[] key, Func`3 handerAsync)
--- End of inner exception stack trace ---
    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at MNJ.UnitTest.RedisClientTest.TestDelAsync() in  Test method MNJ.UnitTest.RedisClientTest.TestDelAsync threw exception: 
System.AggregateException: One or more errors occurred. (CROSSSLOT Keys in request don't hash to the same slot) ---> CSRedis.RedisException: CROSSSLOT Keys in request don't hash to the same slot
结果 StandardOutput:	csreids 错误【192.168.177.71:6379/0】：CROSSSLOT Keys in request don't hash to the same slot    at CSRedis.CSRedisClient.GetAndExecuteAsync[T](RedisClientPool pool, Func`2 handerAsync, Int32 jump, Int32 errtimes)

测试代码：
        [TestMethod]
        public void TestDelAsync()
        {
            Task<long> result = this.redisClient.DelAsync("Key1","Key2");
            result.Wait();
            Assert.AreEqual(0, result.Result);
        }

是异步接口不支持跨slot操作吗？

**Comment by 2881099** [comment]
是的，集群限制。

**Comment by 2881099** [comment]
没有预热的 key + slot 会使用 nodes[0] 进行执行；
如果预热后 CSRedisClient 会根据 slot 缓存分开请求各节点删除的。当然slot中途发生变化时，CSRedisClient 中的缓存未更新时，也会发生此错误：ROSSSLOT Keys in request don't hash to the same slot

预热slot缓存方法：可以通过循环任意key操作。如：rds.Get(Guid.NewGuid().ToString())。

**Comment by 2881099** [comment]
查看 slot 缓存情况：

```csharp
		[HttpGet(@"connection/redis")]
		public ContentResult Get_connection_redis() {
			var sb = new StringBuilder();
			foreach(var pool in RedisHelper.Nodes.Values) {
				sb.AppendLine($@"【{pool.Policy.Name}】　　状态：{(pool.IsAvailable ? "正常" : $"[{pool.UnavailableTime}] {pool.UnavailableException.Message}")}
-------------------------------------------------------------------------------------------------------
Slots：{RedisHelper.Instance.SlotCache.Count}/16384, {pool.StatisticsFullily}
");
			}
			return new ContentResult { ContentType = "text/plan;charset=utf-8", Content = sb.ToString() };
		}
```

**Comment by 2881099** [comment]
最稳的办法是循环调用 rds.DelAsync(key)，不使用一次传多 key 的办法。

**Comment by MichaelRWP** [comment]
没有设置preheat参数，默认是预热的，测试时间段内有没有节点上下限，所以slot没有改变。
请教个问题，为什么同步方法可以跨slot操作，异步不行呢？你说的集群限制，我没懂。谢谢。

**Comment by MichaelRWP** [comment]
可以考虑将集群的slot信息在连接上redis集群后的通过查询集群后缓存在本地，然后通过slotchanged消息更新本地slot缓存，不知道我的方法是否可以行？请指教。谢谢。

**Comment by 2881099** [comment]
集群的特点是将 key 按 crc16 算法进行分区存和取；
执行类型 del key1 key2 这种多个 key 操作命令可能存在跨分区操作，即 key1 key2 不在同一个区时，会报 ROSSSLOT Keys in request don't hash to the same slot 错误；

解决方法：
1、在 key 中使用 {} 使用两个 key 强制划分在同一个分区下，del {key}1 {key}2；
> 键哈希标签原理
>
> 键哈希标签是一种可以让用户指定将一批键都能够被存放在同一个槽中的实现方法，用户唯一要做的就是按照既定规则生成key即可，这个规则是这样的，如果我有对于同一个用户有两种不同含义的两份数据，我只要将他们的键设置为下面即可（使用花括号）：
> 
> abc{userId}def和ghi{userId}jkl

2、在 CSRedisClient 初始化完成的时候预热slot缓存，这个预热并非preheat参数（preheat参数主要是针对连接池）；

```csharp
var rds = new CSRedis.CSRedisClient("127.0.0.1:6379,password=,poolsize=10,preheat=true,writeBuffer=10240,name=test,tryit=1");

var str1 = rds.MGet("str1", "str2"); //报错：ROSSSLOT Keys in request don't hash to the same slot
rds.Set("str1", "普通舱");
rds.Set("str2", "商勡舱");
var str2 = rds.MGet("str1", "str2"); //上面报错的地方注释，按顺序执行到这里不会报错。
```
这里说的正是slot缓存，在rds初始化的时候，执行多key操作。。此时 key: str1, str2，没有缓存，所以都向 nodes1 执行的命令，结果返回了错误。
把报错这行注释后，能运行通过，是因为 key: str1, str2 已经通过 rds.Set 命令将 slot缓存了。

redis-server集群默认是不允许多 key 命令执行；
CSRedisClient 根据 slot 缓存分开请求各节点删除，相当于执行了两次命令：get str1 和 get str2；


同步可以，异步不行的原因可能也是因为slot缓存的顺序关系。

**Comment by 2881099** [comment]
CSRedisClient 按集群协议来开发，slot缓存是根据命令每一次 moved 返回结果来作记录的。

slot缓存量最大是16384，一开始是0，redis-server会返回大量的 moved 结果，伴随着 CSRedisClient 的命令执行次数，缓存量越来越多，moved 的情况会越来越少。

get str1 模拟过程：
connect node1
get str1
moved node2
connect node2
get str1
返回内容

最开始slot缓存不存在的时候，有可能连接两次redis-server来获取内容。

**Comment by 2881099** [comment]
推荐使用【键哈希标签原理】解决多key的操作命令

**Comment by MichaelRWP** [comment]
命令 del key1,key2 在发送这个命令到集群某个节点之前，先通过crc16算法，计算出key1和key2分别所在的slot，然后如果key1，key2的slot分布在两个节点上（这里的节点是redis-server）,则分别发送del key1和del key2命令到所在节点，不知这样是否可行？

**Comment by 2881099** [comment]
现在是这样的呀，只因 slot缓存 不存在算不出所在节点。
> crc16只能算出slot值，但不出对应的节点。
slot缓存只能通过redis-server返回moved更新。

**Comment by MichaelRWP** [comment]
可以通过客户端连接初始化的时候，通过 cluster nodes 命令获取集群slot分布信息吗？

**Comment by MichaelRWP** [comment]
192.168.177.71:6379> cluster nodes
134b37aa9a23f6982fd110cc72f2a408fc60b4cb 192.168.177.71:6379@16379 myself,slave a8a7c4c9297a58591321a4bdeee2501f6e985607 0 1550737301000 1 connected
f41f126ce4a0ef27fa048f33f0da8dc796c2da3b 192.168.177.72:6379@16379 master - 0 1550737300402 3 connected 5461-10922
a8276001368a6be6cc26a6818a460db53075f0ca 192.168.177.73:6379@16379 master - 0 1550737299398 5 connected 10923-16383
169882cb7bcda68cf9971ac9da9342fd410b9107 192.168.177.71:6380@16380 slave f41f126ce4a0ef27fa048f33f0da8dc796c2da3b 0 1550737299000 3 connected
a8a7c4c9297a58591321a4bdeee2501f6e985607 192.168.177.73:6380@16380 master - 0 1550737300000 7 connected 0-5460
536bd3798a92f9f289320ec5f38810fd06a8679f 192.168.177.72:6380@16380 slave a8276001368a6be6cc26a6818a460db53075f0ca 0 1550737301405 5 connected

**Comment by MichaelRWP** [comment]
不知这样是否可行？

**Comment by 2881099** [comment]
可行。需要等更新。。。
用另一个方法不需要等更新，循环一定次数 rds.Get(Guid.NewGuid().ToString())

**Comment by MichaelRWP** [comment]
好的。谢谢。占用你大量时间解答我的疑问，不好意思。

**Comment by 2881099** [comment]
没事，我按照你给的思路，在CSRedisClient内执行cluster nodes完成初始化工作。

**Comment by 2881099** [comment]
输入错误：git 提交说明【现实】=【实现】

v3.0.39 集群模式slot缓存，多key命令已按你的想法执行，不会报错。

**Comment by drakefang** [comment]
求教,v 3.1.8, HDel出现这个问题也是因为hash下不同的key也会放在不同的节点导致吗?

**Comment by 2881099** [comment]
@drakefang
HDel 没有这个问题，详细问题描述一下，开新issues
