### ISSUE TITLE
状态不可用,Connection was not opened

### ISSUE THREAD

**Issue by male110** [2881099/csredis#94]
System.Exception: 【127.0.0.1:6379/0】状态不可用，等待后台检查程序恢复方可使用。
Connection was not opened     at SafeObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)     
at SafeObjectPool.ObjectPool`1.Get(Nullable`1 timeout)    
 at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump)    
 at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)     at CSRedis.CSRedisClient.Exists(String key)     
 at RedisHelper.Exists(String key)

**Comment by 2881099** [comment]
网络环境问题。

**Comment by chiikin** [comment]
CSRedisCore使用非常方便。但是最近部署到服务器上测试时，同样发现了这个问题。

发现两个问题，在redis和CSRedis全部使用默认配置的情况下：
1. 由于是分布式架构，包括十几个端点，服务全部起来后，连接数在500~2000之间时都会报这个错误；（不设置IdleTime一个进程结束之后，不一定返还连接）
2. 一个程序如果出现此错误，除非结束进程，否则在很长时间内无法回复，持续报错。
3. 其他程序仍然能够正常访问。

环境：windows server 2012 R2/ dotnetcore 2.1.3
驱动版本：csrediscore\3.1.14
使用方法：（startup时，一次性调用，后续使用Redishelper.Get等）
`        public static void InitializationCSRedisClient(string redisConnectionString)
        {
            //使用单例模式即可
            var cs = new CSRedis.CSRedisClient(redisConnectionString);
            RedisHelper.Initialization(cs);
        }
`

服务器和redis都在同一台服务器上。请帮忙看看是什么问题，谢谢。

**Comment by 2881099** [comment]
idletimeout 连接串这个参数设置了没有

**Comment by chiikin** [comment]
没有，我直接设置了redis的配置，然后连接数下来了。但是我这个程序还是有问题，我也持续在自查。
设置idletimeout 这个参数的话，有什么推荐值吗

**Comment by 2881099** [comment]
小于redis idle设置，30秒比较合适

**Comment by 2881099** [comment]
默认是长连接，如果设置了这个后30秒没使用，销毁socket，创建新的socket通道发送命令

**Comment by chiikin** [comment]
谢谢，设置了，连接数现在不到100，但是还是报错（略有不同，但是redis初始化时候成功没有报错）。
CSRedis.RedisClientException: Connection was not opened
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
我先排查下自己的问题，目前这个webapi多次重启都无法解决。

**Comment by 2881099** [comment]
idleTimeout=20000

单位是毫秒

**Comment by chiikin** [comment]
我们还在观察，现在并没有完全解决问题。

**Comment by 2881099** [comment]
还有这个错误吗？CSRedis.RedisClientException: Connection was not opened

**Comment by chiikin** [comment]
是的，不稳定。还是会报异常“CSRedis.RedisClientException: Connection was not opened”

**Comment by chiikin** [comment]
我们排查了一下，发现可能是连接字符串的问题.原连接字符串：
`****:6379,allowAdmin=true,password=****,defaultdatabase=3;`

报错是：
System.Exception: 【****:6379/0】状态不可用，等待后台检查程序恢复方可使用。Connection was not opened

然后我们发现我们的连接字符串最后多了`;`这个字符。但是我们现在无法还原异常出现的状况，所以还未知道是否是因为指定的数据库配置导致异常的发生还是其他问题。

**Comment by 2881099** [comment]
****:6379,password=****,defaultdatabase=3,idleTimeout=20000,preheat=3,tryit=2

用这个试试

**Comment by chiikin** [comment]
经过一段时间的监控，问题不再出现，所以我们认为是我们写的连接字符串不正确，在`defaultdatabase`配置项后多了分号，导致数据库配置解析错误。

**Comment by 2881099** [comment]
> 经过一段时间的监控，问题不再出现，所以我们认为是我们写的连接字符串不正确，在`defaultdatabase`配置项后多了分号，导致数据库配置解析错误。

好的，感谢反馈
