### ISSUE TITLE
恢复检查时间

### ISSUE THREAD

**Issue by zsy619** [2881099/csredis#96]
redis集群链接字符串：
10.10.50.3:7000,writeBuffer=60480;10.10.50.2:7000,writeBuffer=60480;10.10.50.3:7001,writeBuffer=60480
出现的异常：
CSRedis.RedisClientException: Connection was not opened
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Exists(String key)
   at TxSms.MP.Web.Areas.Logs.Controllers.TrackController.GetInfo(String id) in E:\sms2018\TxSms.MP\src\TxSms.MP.Web\Areas\Logs\Controllers\TrackController.cs:line 178
【10.10.50.2:6379/0】恢复检查时间：3/1/2019 9:30:12 AM
【10.10.50.2:6379/0】仍然不可用，下一次恢复检查时间：3/1/2019 9:30:19 AM，错误：(Connection was not opened)
【10.10.50.2:6379/0】已恢复工作

没有6389这个端口，具体是什么原因？？？

**Comment by 2881099** [comment]
> 127.0.0.1:6379,password=123,poolsize=50,prefix=

集群在字符串使用任何一个节点即可

**Comment by 2881099** [comment]
var rds = new CSRedisClient("10.10.50.3:7000,password=123,poolsize=50,
writeBuffer=6048,prefix=");

这样就是集群，其他节点在运行中会自动附加进不，不需要在初始化配置全部。

**Comment by zsy619** [comment]
@2881099 群主，nuget上版本是3.0.40 源码是3.0.41 ，什么时候更新上去

**Comment by 2881099** [comment]
40 没什么问题，41 变动很小等下次与其他一起发布

**Comment by liuyl1992** [comment]
> var rds = new CSRedisClient("10.10.50.3:7000,password=123,poolsize=50,
> writeBuffer=6048,prefix=");
> 
> 这样就是集群，其他节点在运行中会自动附加进来，不需要在初始化配置全部。

如果初始化全部了会怎样

**Comment by 2881099** [comment]
@liuyl1992 不会怎样，后面换服务器可能麻烦一些
